# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the client CLI reference page from the argparse parsers.

The client ``argsfactory`` parsers are the single source of truth for the
command-line interface, so this script renders them into
``docs/source/cli_reference.rst``. Generating the page from code keeps the
documented options from drifting away from the actual flags and defaults.

Regenerate the page after changing any client CLI::

    source .venv/bin/activate
    python scripts/docs/generate_cli_reference.py

Verify the committed page is current (used by the docs consistency test)::

    python scripts/docs/generate_cli_reference.py --check

Examples:
    >>> rst = render_cli_reference()
    >>> rst.startswith(".. _cli_reference:")
    True
"""

import argparse
import importlib
import sys
import textwrap
from pathlib import Path

# Add the project source roots to ``sys.path`` so the client argument modules
# import the same way they do under pytest and inside the services. This lets
# the script run from any working directory. Order matters: ``src`` must come
# before ``client`` so the top-level ``common`` package resolves to
# ``src/common`` and not the unrelated ``client/common`` helper package.
_REPO_ROOT = Path(__file__).resolve().parents[2]
_SOURCE_ROOTS = (
    _REPO_ROOT,
    _REPO_ROOT / "src",
    _REPO_ROOT / "client",
    _REPO_ROOT / "protos" / "generated",
)
_existing_paths = set(sys.path)
sys.path[:0] = [str(_root) for _root in _SOURCE_ROOTS if str(_root) not in _existing_paths]

OUTPUT_PATH = _REPO_ROOT / "docs" / "source" / "cli_reference.rst"

# Each entry: (section title, module path, factory attribute, example command).
# Order is fixed so the rendered page is deterministic.
_CLIENTS = (
    (
        "Controller Client",
        "client.controller.args",
        "argsfactory",
        "python client/controller/app.py",
    ),
    (
        "Direct Client",
        "client.direct.args",
        "argsfactory",
        "python client/direct/app.py",
    ),
    (
        "S2S Client",
        "client.s2s.args",
        "argsfactory",
        "python client/s2s/app.py",
    ),
    (
        "ASD Client",
        "client.asd.args",
        "argsfactory",
        "python client/asd/app.py",
    ),
    (
        "LipSync Client",
        "client.lipsync.args",
        "argsfactory",
        "python client/lipsync/app.py",
    ),
    (
        "Batch Processing Client",
        "client.batch_processing.args",
        "argsfactory",
        "python -m client.batch_processing.app",
    ),
)

_HEADER_LINES = (
    ".. _cli_reference:",
    "",
    ".. Generated by scripts/docs/generate_cli_reference.py -- do not edit by hand.",
    "",
    "=============",
    "CLI Reference",
    "=============",
    "",
    "Command-line options for every client, generated directly from the",
    "``argsfactory`` argument parsers.",
    "Run ``python <client>/app.py --help`` for the authoritative live listing.",
    "",
)


def _option_meta(action: argparse.Action) -> str:
    """Build the parenthetical metadata (default/choices) for one option.

    Args:
        action (argparse.Action): A single argparse action (one CLI option).

    Returns:
        str: A string like ``(default: ``en``; choices: ``a``, ``b``)`` or an
            empty string when there is no metadata to show. Flags (store-true
            style actions with ``nargs == 0``) are reported as ``(flag)``.

    Examples:
        >>> parser = argparse.ArgumentParser()
        >>> _ = parser.add_argument("--lang", default="en")
        >>> _option_meta(parser._actions[-1])
        '(default: ``en``)'
    """
    meta: list[str] = []
    if action.nargs == 0:
        # store_true / store_false flags carry no value.
        meta.append("flag")
    elif action.default is argparse.SUPPRESS:
        pass
    elif action.default is None:
        meta.append("default: ``None``")
    else:
        meta.append(f"default: ``{action.default}``")
    if action.choices:
        rendered_choices = ", ".join(f"``{choice}``" for choice in action.choices)
        meta.append(f"choices: {rendered_choices}")
    return f"({'; '.join(meta)})" if meta else ""


def _render_option(action: argparse.Action) -> str:
    """Render a single CLI option as a wrapped reStructuredText bullet.

    Args:
        action (argparse.Action): A single argparse action (one CLI option).

    Returns:
        str: A bullet line (possibly wrapped onto continuation lines indented
            by two spaces) under 100 characters per line.

    Examples:
        >>> parser = argparse.ArgumentParser()
        >>> _ = parser.add_argument("--lang", default="en", help="Source language.")
        >>> _render_option(parser._actions[-1])
        '* ``--lang`` (default: ``en``) -- Source language.'
    """
    label = "/".join(f"``{option}``" for option in action.option_strings)
    meta = _option_meta(action)
    help_text = " ".join((action.help or "").split())
    parts = [label]
    if meta:
        parts.append(meta)
    line = " ".join(parts)
    if help_text:
        line = f"{line} -- {help_text}"
    # break_long_words/break_on_hyphens are disabled so inline ``literals`` and
    # hyphenated option names are never split across lines (RST inline markup
    # cannot span line boundaries).
    return textwrap.fill(
        line,
        width=96,
        initial_indent="* ",
        subsequent_indent="  ",
        break_long_words=False,
        break_on_hyphens=False,
    )


def _render_client(title: str, module_name: str, factory_name: str, command: str) -> list[str]:
    """Render one client's section (heading, command, and option bullets).

    Args:
        title (str): Human-readable section title (e.g. ``"S2S Client"``).
        module_name (str): Importable module path holding the parser factory.
        factory_name (str): Name of the zero-argument factory returning the
            ``argparse.ArgumentParser``.
        command (str): Example invocation shown under the heading.

    Returns:
        list[str]: The reStructuredText lines for this client section.

    Examples:
        >>> lines = _render_client(
        ...     title="S2S Client",
        ...     module_name="client.s2s.args",
        ...     factory_name="argsfactory",
        ...     command="python client/s2s/app.py",
        ... )
        >>> lines[0]
        'S2S Client'
    """
    module = importlib.import_module(module_name)
    parser = getattr(module, factory_name)()
    lines = [title, "~" * len(title), "", f"Command: ``{command}``", ""]
    for action in parser._actions:
        if not action.option_strings:
            # Skip positionals; clients only define optional arguments.
            continue
        if any(option in ("-h", "--help") for option in action.option_strings):
            continue
        lines.append(_render_option(action))
    lines.append("")
    return lines


def render_cli_reference() -> str:
    """Render the full CLI reference page as reStructuredText.

    Returns:
        str: The complete ``cli_reference.rst`` contents, terminated by a
            single trailing newline.

    Examples:
        >>> render_cli_reference().splitlines()[0]
        '.. _cli_reference:'
    """
    lines = list(_HEADER_LINES)
    for title, module_name, factory_name, command in _CLIENTS:
        lines.extend(
            _render_client(
                title=title,
                module_name=module_name,
                factory_name=factory_name,
                command=command,
            )
        )
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write (or, with ``--check``, verify) the generated CLI reference page.

    Args:
        argv (list[str] | None): Optional argument vector for testing. Uses
            ``sys.argv`` when ``None``.

    Returns:
        int: ``0`` on success; ``1`` when ``--check`` finds a stale page.

    Examples:
        >>> main(["--check"])  # doctest: +SKIP
        0
    """
    parser = argparse.ArgumentParser(description="Generate the client CLI reference page.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed page differs from freshly generated output.",
    )
    args = parser.parse_args(argv)
    rendered = render_cli_reference()
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{OUTPUT_PATH} is out of date. Regenerate with "
                "`python scripts/docs/generate_cli_reference.py`.",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
