#!/bin/bash
#
# Quick Start Script for Ray Cluster Deployment
#
# This script helps you set up and deploy a Ray cluster on CML quickly.
# It guides you through configuration and deployment.
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Banner
print_banner() {
    echo -e "${BLUE}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║        Ray Cluster Deployment on CML - Quick Start           ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Help function
print_help() {
    cat <<EOF
Usage: quick_start.sh [OPTIONS]

OPTIONS:
    -h, --help              Show this help message
    -d, --deploy            Deploy to CML (requires env vars)
    -c, --configure         Configure settings only
    --skip-validation       Skip environment validation
    --force-rebuild         Force rebuild (skip cache)

EXAMPLES:
    # Interactive setup and configuration
    ./quick_start.sh

    # Direct deployment
    ./quick_start.sh -d

    # Configure only
    ./quick_start.sh -c

ENVIRONMENT VARIABLES (required for -d):
    CML_HOST                CML instance URL
    CML_API_KEY             CML API authentication key

OPTIONAL:
    GITHUB_REPOSITORY       GitHub repo (owner/repo)
    GH_PAT                  GitHub token
    RUNTIME_IDENTIFIER      Docker runtime image

EOF
}

# Validation function
validate_environment() {
    echo -e "\n${BLUE}Validating environment...${NC}"

    if [ -z "$CML_HOST" ]; then
        echo -e "${RED}✗ CML_HOST not set${NC}"
        return 1
    else
        echo -e "${GREEN}✓ CML_HOST: $CML_HOST${NC}"
    fi

    if [ -z "$CML_API_KEY" ]; then
        echo -e "${RED}✗ CML_API_KEY not set${NC}"
        return 1
    else
        # Show masked key
        key_length=${#CML_API_KEY}
        masked_key="***${CML_API_KEY: -4}"
        echo -e "${GREEN}✓ CML_API_KEY: $masked_key (${key_length} chars)${NC}"
    fi

    # Test connectivity
    echo -e "\n${BLUE}Testing CML connectivity...${NC}"
    if curl -s -H "Authorization: Bearer $CML_API_KEY" \
            "$CML_HOST/api/v2/projects?page_size=1" > /dev/null; then
        echo -e "${GREEN}✓ CML connection successful${NC}"
    else
        echo -e "${RED}✗ Failed to connect to CML${NC}"
        return 1
    fi

    return 0
}

# Interactive configuration
configure_interactively() {
    echo -e "\n${BLUE}Ray Cluster Configuration${NC}"

    # Number of workers
    read -p "Number of Ray worker nodes [1]: " num_workers
    num_workers=${num_workers:-1}

    # Head resources
    read -p "Head node CPU cores [4]: " head_cpu
    head_cpu=${head_cpu:-4}

    read -p "Head node memory (GB) [16]: " head_memory
    head_memory=${head_memory:-16}

    # Worker resources
    read -p "Worker CPU cores [8]: " worker_cpu
    worker_cpu=${worker_cpu:-8}

    read -p "Worker memory (GB) [32]: " worker_memory
    worker_memory=${worker_memory:-32}

    read -p "Worker GPUs (0 for CPU-only) [1]: " worker_gpus
    worker_gpus=${worker_gpus:-1}

    # Update configuration file
    config_file="../configs/ray_cluster_config.yaml"

    cat > "$config_file" <<EOF
# Ray Cluster Configuration
# Generated by quick_start.sh on $(date)

ray_cluster:
  num_workers: $num_workers
  head_cpu: $head_cpu
  head_memory: $head_memory
  worker_cpu: $worker_cpu
  worker_memory: $worker_memory
  worker_gpus: $worker_gpus
  ray_port: 6379
  dashboard_port: 8265

cai:
  runtime_identifier: "docker.repository.cloudera.com/cloudera/cdsw/ml-runtime-pbj-jupyterlab-python3.11-standard:2026.01.1-b6"
  project_name: "ray-cluster"
EOF

    echo -e "\n${GREEN}✓ Configuration saved to: $config_file${NC}"

    # Print summary
    echo -e "\n${BLUE}Configuration Summary:${NC}"
    echo "  Cluster:"
    echo "    Workers: $num_workers"
    echo "    Head: ${head_cpu}CPU, ${head_memory}GB RAM, 0GPU"
    echo "    Workers: ${worker_cpu}CPU, ${worker_memory}GB RAM, ${worker_gpus}GPU each"
}

# Deployment function
deploy() {
    echo -e "\n${BLUE}Starting Ray Cluster Deployment...${NC}"

    if [ -z "$SKIP_VALIDATION" ]; then
        if ! validate_environment; then
            echo -e "\n${RED}Environment validation failed${NC}"
            echo "Please set required environment variables:"
            echo "  export CML_HOST='https://ml.example.cloudera.site'"
            echo "  export CML_API_KEY='your-api-key'"
            return 1
        fi
    fi

    echo -e "\n${BLUE}Deploying Ray cluster...${NC}"
    echo "This may take 5-15 minutes depending on cluster size and resources."
    echo ""

    # Step 1: Setup project
    echo -e "${BLUE}Step 1: Setting up CML project...${NC}"
    if ! python setup_project.py; then
        echo -e "${RED}✗ Project setup failed${NC}"
        return 1
    fi
    PROJECT_ID=$(cat /tmp/project_id.txt)
    echo -e "${GREEN}✓ Project ready: $PROJECT_ID${NC}\n"

    # Step 2: Create jobs
    echo -e "${BLUE}Step 2: Creating CML jobs...${NC}"
    if ! python create_jobs.py --project-id "$PROJECT_ID"; then
        echo -e "${RED}✗ Job creation failed${NC}"
        return 1
    fi
    echo -e "${GREEN}✓ Jobs created${NC}\n"

    # Step 3: Trigger deployment
    echo -e "${BLUE}Step 3: Triggering deployment jobs...${NC}"
    if [ "$FORCE_REBUILD" = "true" ]; then
        export FORCE_REBUILD=true
    fi

    if ! python trigger_jobs.py --project-id "$PROJECT_ID" --jobs-config jobs_config.yaml; then
        echo -e "${RED}✗ Deployment execution failed${NC}"
        return 1
    fi

    echo -e "\n${GREEN}✓ Ray cluster deployment successful!${NC}"
    echo -e "\n${BLUE}Next Steps:${NC}"
    echo "  1. Monitor Ray cluster: http://head-address:8265"
    echo "  2. Check cluster info: cat /home/cdsw/ray_cluster_info.json"
    echo "  3. Connect from Python:"
    echo "     import ray"
    echo "     ray.init(address='ray://head-address:6379')"
    return 0
}

# Main flow
main() {
    print_banner

    # Parse arguments
    case "${1:-}" in
        -h|--help)
            print_help
            exit 0
            ;;
        -d|--deploy)
            deploy
            exit $?
            ;;
        -c|--configure)
            configure_interactively
            exit 0
            ;;
        --skip-validation)
            SKIP_VALIDATION=true
            deploy
            exit $?
            ;;
        --force-rebuild)
            FORCE_REBUILD=true
            deploy
            exit $?
            ;;
    esac

    # Default interactive flow
    echo "Welcome to the Ray Cluster deployment setup!"
    echo ""

    # Check if we have required env vars
    if [ -z "$CML_HOST" ] || [ -z "$CML_API_KEY" ]; then
        echo -e "${YELLOW}Required environment variables not set.${NC}"
        echo ""
        echo "Set them now:"
        echo "  export CML_HOST='https://ml.your-company.cloudera.site'"
        echo "  export CML_API_KEY='your-api-key'"
        echo ""
        read -p "Press Enter after setting environment variables, or Ctrl+C to cancel..."
    fi

    # Configure
    configure_interactively

    # Ask to deploy
    echo ""
    read -p "Deploy to CML now? (y/n) [n]: " should_deploy
    if [ "$should_deploy" = "y" ] || [ "$should_deploy" = "Y" ]; then
        deploy
    else
        echo -e "\n${BLUE}To deploy later, run:${NC}"
        echo "  ./quick_start.sh -d"
        echo ""
        echo "Or manually:"
        echo "  python setup_project.py"
        echo "  PROJECT_ID=\$(cat /tmp/project_id.txt)"
        echo "  python create_jobs.py --project-id \$PROJECT_ID"
        echo "  python trigger_jobs.py --project-id \$PROJECT_ID --jobs-config jobs_config.yaml"
    fi
}

# Run main
main "$@"
