// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v7.35.1
// source: nvidia/ai4m/lipsync/v1/lipsync.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../../../google/protobuf/empty";
import { AudioCodec, audioCodecFromJSON, audioCodecToJSON } from "../../audio/v1/audio";
import { BoundingBox } from "../../common/v1/common";
import { VideoEncoding } from "../../video/v1/video";

export const protobufPackage = "nvidia.ai4m.lipsync.v1";

/**
 * ExtendAudio defines how to handle cases where video duration
 * exceeds audio duration
 */
export enum ExtendAudio {
  /** EXTEND_AUDIO_UNSPECIFIED - Default behavior, no audio extension */
  EXTEND_AUDIO_UNSPECIFIED = 0,
  /** EXTEND_AUDIO_SILENCE - Extend audio with silence to match video length */
  EXTEND_AUDIO_SILENCE = 1,
  UNRECOGNIZED = -1,
}

export function extendAudioFromJSON(object: any): ExtendAudio {
  switch (object) {
    case 0:
    case "EXTEND_AUDIO_UNSPECIFIED":
      return ExtendAudio.EXTEND_AUDIO_UNSPECIFIED;
    case 1:
    case "EXTEND_AUDIO_SILENCE":
      return ExtendAudio.EXTEND_AUDIO_SILENCE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ExtendAudio.UNRECOGNIZED;
  }
}

export function extendAudioToJSON(object: ExtendAudio): string {
  switch (object) {
    case ExtendAudio.EXTEND_AUDIO_UNSPECIFIED:
      return "EXTEND_AUDIO_UNSPECIFIED";
    case ExtendAudio.EXTEND_AUDIO_SILENCE:
      return "EXTEND_AUDIO_SILENCE";
    case ExtendAudio.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * ExtendVideo defines how to handle cases where audio duration
 * exceeds video duration
 */
export enum ExtendVideo {
  /** EXTEND_VIDEO_UNSPECIFIED - Default behavior, no video extension */
  EXTEND_VIDEO_UNSPECIFIED = 0,
  /** EXTEND_VIDEO_FORWARD - Loop video forward to match audio length */
  EXTEND_VIDEO_FORWARD = 1,
  /** EXTEND_VIDEO_REVERSE - Loop video in reverse to match audio length */
  EXTEND_VIDEO_REVERSE = 2,
  UNRECOGNIZED = -1,
}

export function extendVideoFromJSON(object: any): ExtendVideo {
  switch (object) {
    case 0:
    case "EXTEND_VIDEO_UNSPECIFIED":
      return ExtendVideo.EXTEND_VIDEO_UNSPECIFIED;
    case 1:
    case "EXTEND_VIDEO_FORWARD":
      return ExtendVideo.EXTEND_VIDEO_FORWARD;
    case 2:
    case "EXTEND_VIDEO_REVERSE":
      return ExtendVideo.EXTEND_VIDEO_REVERSE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ExtendVideo.UNRECOGNIZED;
  }
}

export function extendVideoToJSON(object: ExtendVideo): string {
  switch (object) {
    case ExtendVideo.EXTEND_VIDEO_UNSPECIFIED:
      return "EXTEND_VIDEO_UNSPECIFIED";
    case ExtendVideo.EXTEND_VIDEO_FORWARD:
      return "EXTEND_VIDEO_FORWARD";
    case ExtendVideo.EXTEND_VIDEO_REVERSE:
      return "EXTEND_VIDEO_REVERSE";
    case ExtendVideo.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Background Audio config */
export interface BackgroundAudioConfig {
  /**
   * Indicates whether background audio is provided for mixing.
   * If true, background audio will be mixed with the output
   * to preserve ambient sounds.
   * If false or unset, only the main audio will be used.
   */
  is_background_audio_provided?:
    | boolean
    | undefined;
  /** Background audio's codec */
  audio_codec?:
    | AudioCodec
    | undefined;
  /**
   * Background audio volume to be used for mixing.
   * 0: Background audio is not included.
   * 1: Background audio is included at its full, original volume.
   * (0, 1): Background volume is reduced (a value between 0 and 1).
   */
  audio_volume?: number | undefined;
}

/**
 * LipsyncConfig contains configuration parameters for the
 * lip sync animation
 */
export interface LipsyncConfig {
  /** Codec of the input audio (wav or mp3) */
  input_audio_codec: AudioCodec;
  /**
   * Indicates whether speaker information is provided by the user
   * If true, the user provides speaker bounding boxes and metadata
   * If false or unset, the system will auto-detect faces
   */
  is_speaker_info_provided?:
    | boolean
    | undefined;
  /** How to handle longer video than audio */
  extend_audio?:
    | ExtendAudio
    | undefined;
  /** How to handle longer audio than video */
  extend_video?:
    | ExtendVideo
    | undefined;
  /** Output video encoding parameters */
  output_video_encoding?:
    | VideoEncoding
    | undefined;
  /** Output video's audio codec */
  output_audio_codec?:
    | AudioCodec
    | undefined;
  /**
   * Speed of head movement in input video
   * 0 for static/slow-moving head, 1 for fast-moving head
   */
  head_movement_speed?:
    | number
    | undefined;
  /** Background audio config */
  background_audio_config?: BackgroundAudioConfig | undefined;
}

/**
 * SpeakerInfo contains metadata for tracking and processing
 * a speaker's face region in video frames.
 */
export interface SpeakerInfo {
  /**
   * Bounding box coordinates defining the rectangular region
   * containing the speaker's face
   */
  speaker_bbox:
    | BoundingBox
    | undefined;
  /** Unique identifier for this speaker across frames */
  speaker_id?:
    | number
    | undefined;
  /** Flag indicating whether the speaker is currently speaking */
  is_speaking?: boolean | undefined;
}

/**
 * SpeakerInfoPerFrame contains all speaker face information
 * for a single video frame. Enables targeted lip sync
 * processing for one or multiple speakers per frame.
 */
export interface SpeakerInfoPerFrame {
  /** Frame Index */
  frame_id: number;
  /**
   * List of all speakers detected or provided in this frame
   * Can include multiple speakers for multi-speaker scenarios
   * Each entry contains a bounding box and metadata (speaker_id, is_speaking)
   */
  speaker_infos: SpeakerInfo[];
  /**
   * Bypass lipsync for this frame.
   * If true, lipsync will be bypassed for this video frame.
   * If false or unset, this video frame will be lipsynced.
   */
  bypass?: boolean | undefined;
}

/**
 * LipsyncInputData contains the video, audio, and optional
 * speaker face information for lip sync processing.
 */
export interface LipsyncInputData {
  /** Input video file data as bytes (e.g., MP4 file contents) */
  video_file_data?:
    | Uint8Array
    | undefined;
  /** Input audio file data as bytes (e.g., WAV or MP3 file contents) */
  audio_file_data?:
    | Uint8Array
    | undefined;
  /**
   * Speaker face regions for each video frame (optional)
   * Send one SpeakerInfoPerFrame per video frame, ordered by frame number
   * Leave empty to enable automatic face detection for all frames
   */
  per_frame_speaker_infos: SpeakerInfoPerFrame[];
  /** Bytes of the background audio file */
  background_audio_file_data?: Uint8Array | undefined;
}

/**
 * LipsyncRequest is a union type that can contain either
 * configuration or input data
 */
export interface LipsyncRequest {
  /** Configuration parameters for Lipsync */
  config?:
    | LipsyncConfig
    | undefined;
  /** Input video and audio data to process */
  input?: LipsyncInputData | undefined;
}

/**
 * LipsyncResponse is a union type that can contain
 * configuration, video data, or keepalive
 */
export interface LipsyncResponse {
  /** Echoed configuration parameters */
  config?:
    | LipsyncConfig
    | undefined;
  /** Bytes of the output video file */
  video_file_data?:
    | Uint8Array
    | undefined;
  /** Empty message used to maintain connection */
  keepalive?: Empty | undefined;
}

function createBaseBackgroundAudioConfig(): BackgroundAudioConfig {
  return { is_background_audio_provided: undefined, audio_codec: undefined, audio_volume: undefined };
}

export const BackgroundAudioConfig: MessageFns<BackgroundAudioConfig> = {
  encode(message: BackgroundAudioConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.is_background_audio_provided !== undefined) {
      writer.uint32(8).bool(message.is_background_audio_provided);
    }
    if (message.audio_codec !== undefined) {
      writer.uint32(16).int32(message.audio_codec);
    }
    if (message.audio_volume !== undefined) {
      writer.uint32(29).float(message.audio_volume);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BackgroundAudioConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBackgroundAudioConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.is_background_audio_provided = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.audio_codec = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.audio_volume = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BackgroundAudioConfig {
    return {
      is_background_audio_provided: isSet(object.is_background_audio_provided)
        ? globalThis.Boolean(object.is_background_audio_provided)
        : undefined,
      audio_codec: isSet(object.audio_codec) ? audioCodecFromJSON(object.audio_codec) : undefined,
      audio_volume: isSet(object.audio_volume) ? globalThis.Number(object.audio_volume) : undefined,
    };
  },

  toJSON(message: BackgroundAudioConfig): unknown {
    const obj: any = {};
    if (message.is_background_audio_provided !== undefined) {
      obj.is_background_audio_provided = message.is_background_audio_provided;
    }
    if (message.audio_codec !== undefined) {
      obj.audio_codec = audioCodecToJSON(message.audio_codec);
    }
    if (message.audio_volume !== undefined) {
      obj.audio_volume = message.audio_volume;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BackgroundAudioConfig>, I>>(base?: I): BackgroundAudioConfig {
    return BackgroundAudioConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BackgroundAudioConfig>, I>>(object: I): BackgroundAudioConfig {
    const message = createBaseBackgroundAudioConfig();
    message.is_background_audio_provided = object.is_background_audio_provided ?? undefined;
    message.audio_codec = object.audio_codec ?? undefined;
    message.audio_volume = object.audio_volume ?? undefined;
    return message;
  },
};

function createBaseLipsyncConfig(): LipsyncConfig {
  return {
    input_audio_codec: 0,
    is_speaker_info_provided: undefined,
    extend_audio: undefined,
    extend_video: undefined,
    output_video_encoding: undefined,
    output_audio_codec: undefined,
    head_movement_speed: undefined,
    background_audio_config: undefined,
  };
}

export const LipsyncConfig: MessageFns<LipsyncConfig> = {
  encode(message: LipsyncConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.input_audio_codec !== 0) {
      writer.uint32(8).int32(message.input_audio_codec);
    }
    if (message.is_speaker_info_provided !== undefined) {
      writer.uint32(16).bool(message.is_speaker_info_provided);
    }
    if (message.extend_audio !== undefined) {
      writer.uint32(24).int32(message.extend_audio);
    }
    if (message.extend_video !== undefined) {
      writer.uint32(32).int32(message.extend_video);
    }
    if (message.output_video_encoding !== undefined) {
      VideoEncoding.encode(message.output_video_encoding, writer.uint32(42).fork()).join();
    }
    if (message.output_audio_codec !== undefined) {
      writer.uint32(48).int32(message.output_audio_codec);
    }
    if (message.head_movement_speed !== undefined) {
      writer.uint32(56).uint32(message.head_movement_speed);
    }
    if (message.background_audio_config !== undefined) {
      BackgroundAudioConfig.encode(message.background_audio_config, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LipsyncConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLipsyncConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.input_audio_codec = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.is_speaker_info_provided = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.extend_audio = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.extend_video = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.output_video_encoding = VideoEncoding.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.output_audio_codec = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.head_movement_speed = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.background_audio_config = BackgroundAudioConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LipsyncConfig {
    return {
      input_audio_codec: isSet(object.input_audio_codec) ? audioCodecFromJSON(object.input_audio_codec) : 0,
      is_speaker_info_provided: isSet(object.is_speaker_info_provided)
        ? globalThis.Boolean(object.is_speaker_info_provided)
        : undefined,
      extend_audio: isSet(object.extend_audio) ? extendAudioFromJSON(object.extend_audio) : undefined,
      extend_video: isSet(object.extend_video) ? extendVideoFromJSON(object.extend_video) : undefined,
      output_video_encoding: isSet(object.output_video_encoding)
        ? VideoEncoding.fromJSON(object.output_video_encoding)
        : undefined,
      output_audio_codec: isSet(object.output_audio_codec) ? audioCodecFromJSON(object.output_audio_codec) : undefined,
      head_movement_speed: isSet(object.head_movement_speed)
        ? globalThis.Number(object.head_movement_speed)
        : undefined,
      background_audio_config: isSet(object.background_audio_config)
        ? BackgroundAudioConfig.fromJSON(object.background_audio_config)
        : undefined,
    };
  },

  toJSON(message: LipsyncConfig): unknown {
    const obj: any = {};
    if (message.input_audio_codec !== 0) {
      obj.input_audio_codec = audioCodecToJSON(message.input_audio_codec);
    }
    if (message.is_speaker_info_provided !== undefined) {
      obj.is_speaker_info_provided = message.is_speaker_info_provided;
    }
    if (message.extend_audio !== undefined) {
      obj.extend_audio = extendAudioToJSON(message.extend_audio);
    }
    if (message.extend_video !== undefined) {
      obj.extend_video = extendVideoToJSON(message.extend_video);
    }
    if (message.output_video_encoding !== undefined) {
      obj.output_video_encoding = VideoEncoding.toJSON(message.output_video_encoding);
    }
    if (message.output_audio_codec !== undefined) {
      obj.output_audio_codec = audioCodecToJSON(message.output_audio_codec);
    }
    if (message.head_movement_speed !== undefined) {
      obj.head_movement_speed = Math.round(message.head_movement_speed);
    }
    if (message.background_audio_config !== undefined) {
      obj.background_audio_config = BackgroundAudioConfig.toJSON(message.background_audio_config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LipsyncConfig>, I>>(base?: I): LipsyncConfig {
    return LipsyncConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LipsyncConfig>, I>>(object: I): LipsyncConfig {
    const message = createBaseLipsyncConfig();
    message.input_audio_codec = object.input_audio_codec ?? 0;
    message.is_speaker_info_provided = object.is_speaker_info_provided ?? undefined;
    message.extend_audio = object.extend_audio ?? undefined;
    message.extend_video = object.extend_video ?? undefined;
    message.output_video_encoding =
      (object.output_video_encoding !== undefined && object.output_video_encoding !== null)
        ? VideoEncoding.fromPartial(object.output_video_encoding)
        : undefined;
    message.output_audio_codec = object.output_audio_codec ?? undefined;
    message.head_movement_speed = object.head_movement_speed ?? undefined;
    message.background_audio_config =
      (object.background_audio_config !== undefined && object.background_audio_config !== null)
        ? BackgroundAudioConfig.fromPartial(object.background_audio_config)
        : undefined;
    return message;
  },
};

function createBaseSpeakerInfo(): SpeakerInfo {
  return { speaker_bbox: undefined, speaker_id: undefined, is_speaking: undefined };
}

export const SpeakerInfo: MessageFns<SpeakerInfo> = {
  encode(message: SpeakerInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.speaker_bbox !== undefined) {
      BoundingBox.encode(message.speaker_bbox, writer.uint32(10).fork()).join();
    }
    if (message.speaker_id !== undefined) {
      writer.uint32(16).int32(message.speaker_id);
    }
    if (message.is_speaking !== undefined) {
      writer.uint32(24).bool(message.is_speaking);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeakerInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeakerInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.speaker_bbox = BoundingBox.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.speaker_id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.is_speaking = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeakerInfo {
    return {
      speaker_bbox: isSet(object.speaker_bbox) ? BoundingBox.fromJSON(object.speaker_bbox) : undefined,
      speaker_id: isSet(object.speaker_id) ? globalThis.Number(object.speaker_id) : undefined,
      is_speaking: isSet(object.is_speaking) ? globalThis.Boolean(object.is_speaking) : undefined,
    };
  },

  toJSON(message: SpeakerInfo): unknown {
    const obj: any = {};
    if (message.speaker_bbox !== undefined) {
      obj.speaker_bbox = BoundingBox.toJSON(message.speaker_bbox);
    }
    if (message.speaker_id !== undefined) {
      obj.speaker_id = Math.round(message.speaker_id);
    }
    if (message.is_speaking !== undefined) {
      obj.is_speaking = message.is_speaking;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeakerInfo>, I>>(base?: I): SpeakerInfo {
    return SpeakerInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeakerInfo>, I>>(object: I): SpeakerInfo {
    const message = createBaseSpeakerInfo();
    message.speaker_bbox = (object.speaker_bbox !== undefined && object.speaker_bbox !== null)
      ? BoundingBox.fromPartial(object.speaker_bbox)
      : undefined;
    message.speaker_id = object.speaker_id ?? undefined;
    message.is_speaking = object.is_speaking ?? undefined;
    return message;
  },
};

function createBaseSpeakerInfoPerFrame(): SpeakerInfoPerFrame {
  return { frame_id: 0, speaker_infos: [], bypass: undefined };
}

export const SpeakerInfoPerFrame: MessageFns<SpeakerInfoPerFrame> = {
  encode(message: SpeakerInfoPerFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frame_id !== 0) {
      writer.uint32(8).uint32(message.frame_id);
    }
    for (const v of message.speaker_infos) {
      SpeakerInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.bypass !== undefined) {
      writer.uint32(24).bool(message.bypass);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeakerInfoPerFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeakerInfoPerFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.frame_id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.speaker_infos.push(SpeakerInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.bypass = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeakerInfoPerFrame {
    return {
      frame_id: isSet(object.frame_id) ? globalThis.Number(object.frame_id) : 0,
      speaker_infos: globalThis.Array.isArray(object?.speaker_infos)
        ? object.speaker_infos.map((e: any) => SpeakerInfo.fromJSON(e))
        : [],
      bypass: isSet(object.bypass) ? globalThis.Boolean(object.bypass) : undefined,
    };
  },

  toJSON(message: SpeakerInfoPerFrame): unknown {
    const obj: any = {};
    if (message.frame_id !== 0) {
      obj.frame_id = Math.round(message.frame_id);
    }
    if (message.speaker_infos?.length) {
      obj.speaker_infos = message.speaker_infos.map((e) => SpeakerInfo.toJSON(e));
    }
    if (message.bypass !== undefined) {
      obj.bypass = message.bypass;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeakerInfoPerFrame>, I>>(base?: I): SpeakerInfoPerFrame {
    return SpeakerInfoPerFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeakerInfoPerFrame>, I>>(object: I): SpeakerInfoPerFrame {
    const message = createBaseSpeakerInfoPerFrame();
    message.frame_id = object.frame_id ?? 0;
    message.speaker_infos = object.speaker_infos?.map((e) => SpeakerInfo.fromPartial(e)) || [];
    message.bypass = object.bypass ?? undefined;
    return message;
  },
};

function createBaseLipsyncInputData(): LipsyncInputData {
  return {
    video_file_data: undefined,
    audio_file_data: undefined,
    per_frame_speaker_infos: [],
    background_audio_file_data: undefined,
  };
}

export const LipsyncInputData: MessageFns<LipsyncInputData> = {
  encode(message: LipsyncInputData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.video_file_data !== undefined) {
      writer.uint32(10).bytes(message.video_file_data);
    }
    if (message.audio_file_data !== undefined) {
      writer.uint32(18).bytes(message.audio_file_data);
    }
    for (const v of message.per_frame_speaker_infos) {
      SpeakerInfoPerFrame.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.background_audio_file_data !== undefined) {
      writer.uint32(34).bytes(message.background_audio_file_data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LipsyncInputData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLipsyncInputData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.video_file_data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.audio_file_data = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.per_frame_speaker_infos.push(SpeakerInfoPerFrame.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.background_audio_file_data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LipsyncInputData {
    return {
      video_file_data: isSet(object.video_file_data) ? bytesFromBase64(object.video_file_data) : undefined,
      audio_file_data: isSet(object.audio_file_data) ? bytesFromBase64(object.audio_file_data) : undefined,
      per_frame_speaker_infos: globalThis.Array.isArray(object?.per_frame_speaker_infos)
        ? object.per_frame_speaker_infos.map((e: any) => SpeakerInfoPerFrame.fromJSON(e))
        : [],
      background_audio_file_data: isSet(object.background_audio_file_data)
        ? bytesFromBase64(object.background_audio_file_data)
        : undefined,
    };
  },

  toJSON(message: LipsyncInputData): unknown {
    const obj: any = {};
    if (message.video_file_data !== undefined) {
      obj.video_file_data = base64FromBytes(message.video_file_data);
    }
    if (message.audio_file_data !== undefined) {
      obj.audio_file_data = base64FromBytes(message.audio_file_data);
    }
    if (message.per_frame_speaker_infos?.length) {
      obj.per_frame_speaker_infos = message.per_frame_speaker_infos.map((e) => SpeakerInfoPerFrame.toJSON(e));
    }
    if (message.background_audio_file_data !== undefined) {
      obj.background_audio_file_data = base64FromBytes(message.background_audio_file_data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LipsyncInputData>, I>>(base?: I): LipsyncInputData {
    return LipsyncInputData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LipsyncInputData>, I>>(object: I): LipsyncInputData {
    const message = createBaseLipsyncInputData();
    message.video_file_data = object.video_file_data ?? undefined;
    message.audio_file_data = object.audio_file_data ?? undefined;
    message.per_frame_speaker_infos = object.per_frame_speaker_infos?.map((e) => SpeakerInfoPerFrame.fromPartial(e)) ||
      [];
    message.background_audio_file_data = object.background_audio_file_data ?? undefined;
    return message;
  },
};

function createBaseLipsyncRequest(): LipsyncRequest {
  return { config: undefined, input: undefined };
}

export const LipsyncRequest: MessageFns<LipsyncRequest> = {
  encode(message: LipsyncRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      LipsyncConfig.encode(message.config, writer.uint32(10).fork()).join();
    }
    if (message.input !== undefined) {
      LipsyncInputData.encode(message.input, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LipsyncRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLipsyncRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = LipsyncConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input = LipsyncInputData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LipsyncRequest {
    return {
      config: isSet(object.config) ? LipsyncConfig.fromJSON(object.config) : undefined,
      input: isSet(object.input) ? LipsyncInputData.fromJSON(object.input) : undefined,
    };
  },

  toJSON(message: LipsyncRequest): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = LipsyncConfig.toJSON(message.config);
    }
    if (message.input !== undefined) {
      obj.input = LipsyncInputData.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LipsyncRequest>, I>>(base?: I): LipsyncRequest {
    return LipsyncRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LipsyncRequest>, I>>(object: I): LipsyncRequest {
    const message = createBaseLipsyncRequest();
    message.config = (object.config !== undefined && object.config !== null)
      ? LipsyncConfig.fromPartial(object.config)
      : undefined;
    message.input = (object.input !== undefined && object.input !== null)
      ? LipsyncInputData.fromPartial(object.input)
      : undefined;
    return message;
  },
};

function createBaseLipsyncResponse(): LipsyncResponse {
  return { config: undefined, video_file_data: undefined, keepalive: undefined };
}

export const LipsyncResponse: MessageFns<LipsyncResponse> = {
  encode(message: LipsyncResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      LipsyncConfig.encode(message.config, writer.uint32(10).fork()).join();
    }
    if (message.video_file_data !== undefined) {
      writer.uint32(18).bytes(message.video_file_data);
    }
    if (message.keepalive !== undefined) {
      Empty.encode(message.keepalive, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LipsyncResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLipsyncResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = LipsyncConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.video_file_data = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.keepalive = Empty.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LipsyncResponse {
    return {
      config: isSet(object.config) ? LipsyncConfig.fromJSON(object.config) : undefined,
      video_file_data: isSet(object.video_file_data) ? bytesFromBase64(object.video_file_data) : undefined,
      keepalive: isSet(object.keepalive) ? Empty.fromJSON(object.keepalive) : undefined,
    };
  },

  toJSON(message: LipsyncResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = LipsyncConfig.toJSON(message.config);
    }
    if (message.video_file_data !== undefined) {
      obj.video_file_data = base64FromBytes(message.video_file_data);
    }
    if (message.keepalive !== undefined) {
      obj.keepalive = Empty.toJSON(message.keepalive);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LipsyncResponse>, I>>(base?: I): LipsyncResponse {
    return LipsyncResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LipsyncResponse>, I>>(object: I): LipsyncResponse {
    const message = createBaseLipsyncResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? LipsyncConfig.fromPartial(object.config)
      : undefined;
    message.video_file_data = object.video_file_data ?? undefined;
    message.keepalive = (object.keepalive !== undefined && object.keepalive !== null)
      ? Empty.fromPartial(object.keepalive)
      : undefined;
    return message;
  },
};

export type LipSyncServiceService = typeof LipSyncServiceService;
export const LipSyncServiceService = {
  /**
   * Lipsync is a bidirectional streaming RPC that takes video and audio
   * input and returns a lip synchronized video output.
   * request: Stream of LipsyncRequest messages containing
   * either configuration or input data
   * response: Stream of LipsyncResponse messages containing either
   * configuration, video data, or keepalive
   */
  lipsync: {
    path: "/nvidia.ai4m.lipsync.v1.LipSyncService/Lipsync",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: LipsyncRequest): Buffer => Buffer.from(LipsyncRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): LipsyncRequest => LipsyncRequest.decode(value),
    responseSerialize: (value: LipsyncResponse): Buffer => Buffer.from(LipsyncResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): LipsyncResponse => LipsyncResponse.decode(value),
  },
} as const;

export interface LipSyncServiceServer extends UntypedServiceImplementation {
  /**
   * Lipsync is a bidirectional streaming RPC that takes video and audio
   * input and returns a lip synchronized video output.
   * request: Stream of LipsyncRequest messages containing
   * either configuration or input data
   * response: Stream of LipsyncResponse messages containing either
   * configuration, video data, or keepalive
   */
  lipsync: handleBidiStreamingCall<LipsyncRequest, LipsyncResponse>;
}

export interface LipSyncServiceClient extends Client {
  /**
   * Lipsync is a bidirectional streaming RPC that takes video and audio
   * input and returns a lip synchronized video output.
   * request: Stream of LipsyncRequest messages containing
   * either configuration or input data
   * response: Stream of LipsyncResponse messages containing either
   * configuration, video data, or keepalive
   */
  lipsync(): ClientDuplexStream<LipsyncRequest, LipsyncResponse>;
  lipsync(options: Partial<CallOptions>): ClientDuplexStream<LipsyncRequest, LipsyncResponse>;
  lipsync(metadata: Metadata, options?: Partial<CallOptions>): ClientDuplexStream<LipsyncRequest, LipsyncResponse>;
}

export const LipSyncServiceClient = makeGenericClientConstructor(
  LipSyncServiceService,
  "nvidia.ai4m.lipsync.v1.LipSyncService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): LipSyncServiceClient;
  service: typeof LipSyncServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
