// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v7.35.1
// source: nvidia/ai4m/s2s/v1/s2s.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../../../google/protobuf/empty";

export const protobufPackage = "nvidia.ai4m.s2s.v1";

/** Configuration message for S2S service */
export interface SpeechToSpeechConfig {
  /** Source language for speech-to-speech translation (e.g., "en", "en-US") */
  source_language?:
    | string
    | undefined;
  /** Target language for speech-to-speech translation (e.g., "es", "es-US") */
  target_language?:
    | string
    | undefined;
  /**
   * Voice name for TTS (optional, service will use default if not provided)
   * For zero-shot TTS (transactional mode), the service automatically extracts
   * the first 10 seconds of input audio as the voice reference
   */
  voice_name?:
    | string
    | undefined;
  /** Number of speakers to detect. 0 = auto-detect (ElevenLabs API default). */
  elevenlabs_num_speakers?:
    | number
    | undefined;
  /** Whether to drop background audio from the final dub. */
  elevenlabs_drop_background_audio?:
    | boolean
    | undefined;
  /** [BETA] Whether transcripts should have profanities censored. */
  elevenlabs_use_profanity_filter?:
    | boolean
    | undefined;
  /** [Experimental] Accent to apply when selecting voices and translating. */
  elevenlabs_target_accent?:
    | string
    | undefined;
  /** Whether to use the highest resolution available. */
  elevenlabs_highest_resolution?:
    | boolean
    | undefined;
  /** Whether to apply watermark to the output. */
  elevenlabs_watermark?:
    | boolean
    | undefined;
  /** Whether to prepare dub for edits in dubbing studio. */
  elevenlabs_dubbing_studio?:
    | boolean
    | undefined;
  /** Enable CambAI AI optimization. Default is true when omitted. */
  camb_ai_optimization?:
    | boolean
    | undefined;
  /** CambAI custom dictionary IDs for domain-specific terminology. */
  camb_chosen_dictionaries: number[];
}

/**
 * S2S request stream message.
 *
 * The configuration is sent as the first message of the stream; subsequent
 * messages carry audio data. The audio metadata fields describe the
 * accompanying audio_data payload.
 */
export interface SpeechToSpeechRequest {
  /** Raw audio data */
  audio_data?:
    | Uint8Array
    | undefined;
  /** Configuration for S2S service (sent as the first message) */
  config?:
    | SpeechToSpeechConfig
    | undefined;
  /** Sample rate of the audio (default: 16000) */
  audio_sample_rate?:
    | number
    | undefined;
  /** Number of channels (1 for mono, 2 for stereo) (default: 1) */
  audio_num_channels?:
    | number
    | undefined;
  /** Audio format of audio_data (e.g., "WAV", "MP3") (default: "WAV") */
  audio_format?: string | undefined;
}

/**
 * S2S response stream message.
 *
 * The audio metadata fields describe the accompanying audio_data payload.
 */
export interface SpeechToSpeechResponse {
  /** Raw audio data */
  audio_data?:
    | Uint8Array
    | undefined;
  /** Empty message used to maintain connection (keep-alive) */
  keepalive?:
    | Empty
    | undefined;
  /** Sample rate of the audio (default: 16000) */
  audio_sample_rate?:
    | number
    | undefined;
  /** Number of channels (1 for mono, 2 for stereo) (default: 1) */
  audio_num_channels?:
    | number
    | undefined;
  /** Audio format of audio_data (e.g., "WAV", "MP3") (default: "MP3") */
  audio_format?: string | undefined;
}

function createBaseSpeechToSpeechConfig(): SpeechToSpeechConfig {
  return {
    source_language: undefined,
    target_language: undefined,
    voice_name: undefined,
    elevenlabs_num_speakers: undefined,
    elevenlabs_drop_background_audio: undefined,
    elevenlabs_use_profanity_filter: undefined,
    elevenlabs_target_accent: undefined,
    elevenlabs_highest_resolution: undefined,
    elevenlabs_watermark: undefined,
    elevenlabs_dubbing_studio: undefined,
    camb_ai_optimization: undefined,
    camb_chosen_dictionaries: [],
  };
}

export const SpeechToSpeechConfig: MessageFns<SpeechToSpeechConfig> = {
  encode(message: SpeechToSpeechConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source_language !== undefined) {
      writer.uint32(10).string(message.source_language);
    }
    if (message.target_language !== undefined) {
      writer.uint32(18).string(message.target_language);
    }
    if (message.voice_name !== undefined) {
      writer.uint32(26).string(message.voice_name);
    }
    if (message.elevenlabs_num_speakers !== undefined) {
      writer.uint32(32).int32(message.elevenlabs_num_speakers);
    }
    if (message.elevenlabs_drop_background_audio !== undefined) {
      writer.uint32(40).bool(message.elevenlabs_drop_background_audio);
    }
    if (message.elevenlabs_use_profanity_filter !== undefined) {
      writer.uint32(48).bool(message.elevenlabs_use_profanity_filter);
    }
    if (message.elevenlabs_target_accent !== undefined) {
      writer.uint32(58).string(message.elevenlabs_target_accent);
    }
    if (message.elevenlabs_highest_resolution !== undefined) {
      writer.uint32(64).bool(message.elevenlabs_highest_resolution);
    }
    if (message.elevenlabs_watermark !== undefined) {
      writer.uint32(72).bool(message.elevenlabs_watermark);
    }
    if (message.elevenlabs_dubbing_studio !== undefined) {
      writer.uint32(80).bool(message.elevenlabs_dubbing_studio);
    }
    if (message.camb_ai_optimization !== undefined) {
      writer.uint32(96).bool(message.camb_ai_optimization);
    }
    writer.uint32(106).fork();
    for (const v of message.camb_chosen_dictionaries) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeechToSpeechConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeechToSpeechConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.source_language = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.target_language = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.voice_name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.elevenlabs_num_speakers = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.elevenlabs_drop_background_audio = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.elevenlabs_use_profanity_filter = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.elevenlabs_target_accent = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.elevenlabs_highest_resolution = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.elevenlabs_watermark = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.elevenlabs_dubbing_studio = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.camb_ai_optimization = reader.bool();
          continue;
        }
        case 13: {
          if (tag === 104) {
            message.camb_chosen_dictionaries.push(reader.int32());

            continue;
          }

          if (tag === 106) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.camb_chosen_dictionaries.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeechToSpeechConfig {
    return {
      source_language: isSet(object.source_language) ? globalThis.String(object.source_language) : undefined,
      target_language: isSet(object.target_language) ? globalThis.String(object.target_language) : undefined,
      voice_name: isSet(object.voice_name) ? globalThis.String(object.voice_name) : undefined,
      elevenlabs_num_speakers: isSet(object.elevenlabs_num_speakers)
        ? globalThis.Number(object.elevenlabs_num_speakers)
        : undefined,
      elevenlabs_drop_background_audio: isSet(object.elevenlabs_drop_background_audio)
        ? globalThis.Boolean(object.elevenlabs_drop_background_audio)
        : undefined,
      elevenlabs_use_profanity_filter: isSet(object.elevenlabs_use_profanity_filter)
        ? globalThis.Boolean(object.elevenlabs_use_profanity_filter)
        : undefined,
      elevenlabs_target_accent: isSet(object.elevenlabs_target_accent)
        ? globalThis.String(object.elevenlabs_target_accent)
        : undefined,
      elevenlabs_highest_resolution: isSet(object.elevenlabs_highest_resolution)
        ? globalThis.Boolean(object.elevenlabs_highest_resolution)
        : undefined,
      elevenlabs_watermark: isSet(object.elevenlabs_watermark)
        ? globalThis.Boolean(object.elevenlabs_watermark)
        : undefined,
      elevenlabs_dubbing_studio: isSet(object.elevenlabs_dubbing_studio)
        ? globalThis.Boolean(object.elevenlabs_dubbing_studio)
        : undefined,
      camb_ai_optimization: isSet(object.camb_ai_optimization)
        ? globalThis.Boolean(object.camb_ai_optimization)
        : undefined,
      camb_chosen_dictionaries: globalThis.Array.isArray(object?.camb_chosen_dictionaries)
        ? object.camb_chosen_dictionaries.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: SpeechToSpeechConfig): unknown {
    const obj: any = {};
    if (message.source_language !== undefined) {
      obj.source_language = message.source_language;
    }
    if (message.target_language !== undefined) {
      obj.target_language = message.target_language;
    }
    if (message.voice_name !== undefined) {
      obj.voice_name = message.voice_name;
    }
    if (message.elevenlabs_num_speakers !== undefined) {
      obj.elevenlabs_num_speakers = Math.round(message.elevenlabs_num_speakers);
    }
    if (message.elevenlabs_drop_background_audio !== undefined) {
      obj.elevenlabs_drop_background_audio = message.elevenlabs_drop_background_audio;
    }
    if (message.elevenlabs_use_profanity_filter !== undefined) {
      obj.elevenlabs_use_profanity_filter = message.elevenlabs_use_profanity_filter;
    }
    if (message.elevenlabs_target_accent !== undefined) {
      obj.elevenlabs_target_accent = message.elevenlabs_target_accent;
    }
    if (message.elevenlabs_highest_resolution !== undefined) {
      obj.elevenlabs_highest_resolution = message.elevenlabs_highest_resolution;
    }
    if (message.elevenlabs_watermark !== undefined) {
      obj.elevenlabs_watermark = message.elevenlabs_watermark;
    }
    if (message.elevenlabs_dubbing_studio !== undefined) {
      obj.elevenlabs_dubbing_studio = message.elevenlabs_dubbing_studio;
    }
    if (message.camb_ai_optimization !== undefined) {
      obj.camb_ai_optimization = message.camb_ai_optimization;
    }
    if (message.camb_chosen_dictionaries?.length) {
      obj.camb_chosen_dictionaries = message.camb_chosen_dictionaries.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeechToSpeechConfig>, I>>(base?: I): SpeechToSpeechConfig {
    return SpeechToSpeechConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeechToSpeechConfig>, I>>(object: I): SpeechToSpeechConfig {
    const message = createBaseSpeechToSpeechConfig();
    message.source_language = object.source_language ?? undefined;
    message.target_language = object.target_language ?? undefined;
    message.voice_name = object.voice_name ?? undefined;
    message.elevenlabs_num_speakers = object.elevenlabs_num_speakers ?? undefined;
    message.elevenlabs_drop_background_audio = object.elevenlabs_drop_background_audio ?? undefined;
    message.elevenlabs_use_profanity_filter = object.elevenlabs_use_profanity_filter ?? undefined;
    message.elevenlabs_target_accent = object.elevenlabs_target_accent ?? undefined;
    message.elevenlabs_highest_resolution = object.elevenlabs_highest_resolution ?? undefined;
    message.elevenlabs_watermark = object.elevenlabs_watermark ?? undefined;
    message.elevenlabs_dubbing_studio = object.elevenlabs_dubbing_studio ?? undefined;
    message.camb_ai_optimization = object.camb_ai_optimization ?? undefined;
    message.camb_chosen_dictionaries = object.camb_chosen_dictionaries?.map((e) => e) || [];
    return message;
  },
};

function createBaseSpeechToSpeechRequest(): SpeechToSpeechRequest {
  return {
    audio_data: undefined,
    config: undefined,
    audio_sample_rate: undefined,
    audio_num_channels: undefined,
    audio_format: undefined,
  };
}

export const SpeechToSpeechRequest: MessageFns<SpeechToSpeechRequest> = {
  encode(message: SpeechToSpeechRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audio_data !== undefined) {
      writer.uint32(10).bytes(message.audio_data);
    }
    if (message.config !== undefined) {
      SpeechToSpeechConfig.encode(message.config, writer.uint32(50).fork()).join();
    }
    if (message.audio_sample_rate !== undefined) {
      writer.uint32(24).int32(message.audio_sample_rate);
    }
    if (message.audio_num_channels !== undefined) {
      writer.uint32(32).int32(message.audio_num_channels);
    }
    if (message.audio_format !== undefined) {
      writer.uint32(42).string(message.audio_format);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeechToSpeechRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeechToSpeechRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audio_data = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.config = SpeechToSpeechConfig.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.audio_sample_rate = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.audio_num_channels = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.audio_format = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeechToSpeechRequest {
    return {
      audio_data: isSet(object.audio_data) ? bytesFromBase64(object.audio_data) : undefined,
      config: isSet(object.config) ? SpeechToSpeechConfig.fromJSON(object.config) : undefined,
      audio_sample_rate: isSet(object.audio_sample_rate) ? globalThis.Number(object.audio_sample_rate) : undefined,
      audio_num_channels: isSet(object.audio_num_channels) ? globalThis.Number(object.audio_num_channels) : undefined,
      audio_format: isSet(object.audio_format) ? globalThis.String(object.audio_format) : undefined,
    };
  },

  toJSON(message: SpeechToSpeechRequest): unknown {
    const obj: any = {};
    if (message.audio_data !== undefined) {
      obj.audio_data = base64FromBytes(message.audio_data);
    }
    if (message.config !== undefined) {
      obj.config = SpeechToSpeechConfig.toJSON(message.config);
    }
    if (message.audio_sample_rate !== undefined) {
      obj.audio_sample_rate = Math.round(message.audio_sample_rate);
    }
    if (message.audio_num_channels !== undefined) {
      obj.audio_num_channels = Math.round(message.audio_num_channels);
    }
    if (message.audio_format !== undefined) {
      obj.audio_format = message.audio_format;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeechToSpeechRequest>, I>>(base?: I): SpeechToSpeechRequest {
    return SpeechToSpeechRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeechToSpeechRequest>, I>>(object: I): SpeechToSpeechRequest {
    const message = createBaseSpeechToSpeechRequest();
    message.audio_data = object.audio_data ?? undefined;
    message.config = (object.config !== undefined && object.config !== null)
      ? SpeechToSpeechConfig.fromPartial(object.config)
      : undefined;
    message.audio_sample_rate = object.audio_sample_rate ?? undefined;
    message.audio_num_channels = object.audio_num_channels ?? undefined;
    message.audio_format = object.audio_format ?? undefined;
    return message;
  },
};

function createBaseSpeechToSpeechResponse(): SpeechToSpeechResponse {
  return {
    audio_data: undefined,
    keepalive: undefined,
    audio_sample_rate: undefined,
    audio_num_channels: undefined,
    audio_format: undefined,
  };
}

export const SpeechToSpeechResponse: MessageFns<SpeechToSpeechResponse> = {
  encode(message: SpeechToSpeechResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audio_data !== undefined) {
      writer.uint32(10).bytes(message.audio_data);
    }
    if (message.keepalive !== undefined) {
      Empty.encode(message.keepalive, writer.uint32(58).fork()).join();
    }
    if (message.audio_sample_rate !== undefined) {
      writer.uint32(32).int32(message.audio_sample_rate);
    }
    if (message.audio_num_channels !== undefined) {
      writer.uint32(40).int32(message.audio_num_channels);
    }
    if (message.audio_format !== undefined) {
      writer.uint32(50).string(message.audio_format);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeechToSpeechResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeechToSpeechResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audio_data = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.keepalive = Empty.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.audio_sample_rate = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.audio_num_channels = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.audio_format = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeechToSpeechResponse {
    return {
      audio_data: isSet(object.audio_data) ? bytesFromBase64(object.audio_data) : undefined,
      keepalive: isSet(object.keepalive) ? Empty.fromJSON(object.keepalive) : undefined,
      audio_sample_rate: isSet(object.audio_sample_rate) ? globalThis.Number(object.audio_sample_rate) : undefined,
      audio_num_channels: isSet(object.audio_num_channels) ? globalThis.Number(object.audio_num_channels) : undefined,
      audio_format: isSet(object.audio_format) ? globalThis.String(object.audio_format) : undefined,
    };
  },

  toJSON(message: SpeechToSpeechResponse): unknown {
    const obj: any = {};
    if (message.audio_data !== undefined) {
      obj.audio_data = base64FromBytes(message.audio_data);
    }
    if (message.keepalive !== undefined) {
      obj.keepalive = Empty.toJSON(message.keepalive);
    }
    if (message.audio_sample_rate !== undefined) {
      obj.audio_sample_rate = Math.round(message.audio_sample_rate);
    }
    if (message.audio_num_channels !== undefined) {
      obj.audio_num_channels = Math.round(message.audio_num_channels);
    }
    if (message.audio_format !== undefined) {
      obj.audio_format = message.audio_format;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeechToSpeechResponse>, I>>(base?: I): SpeechToSpeechResponse {
    return SpeechToSpeechResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeechToSpeechResponse>, I>>(object: I): SpeechToSpeechResponse {
    const message = createBaseSpeechToSpeechResponse();
    message.audio_data = object.audio_data ?? undefined;
    message.keepalive = (object.keepalive !== undefined && object.keepalive !== null)
      ? Empty.fromPartial(object.keepalive)
      : undefined;
    message.audio_sample_rate = object.audio_sample_rate ?? undefined;
    message.audio_num_channels = object.audio_num_channels ?? undefined;
    message.audio_format = object.audio_format ?? undefined;
    return message;
  },
};

/** Speech to Speech service definition */
export type SpeechToSpeechService = typeof SpeechToSpeechService;
export const SpeechToSpeechService = {
  /** Bidirectional streaming RPC for speech-to-speech conversion */
  streamSpeechToSpeech: {
    path: "/nvidia.ai4m.s2s.v1.SpeechToSpeech/StreamSpeechToSpeech",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: SpeechToSpeechRequest): Buffer =>
      Buffer.from(SpeechToSpeechRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SpeechToSpeechRequest => SpeechToSpeechRequest.decode(value),
    responseSerialize: (value: SpeechToSpeechResponse): Buffer =>
      Buffer.from(SpeechToSpeechResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SpeechToSpeechResponse => SpeechToSpeechResponse.decode(value),
  },
} as const;

export interface SpeechToSpeechServer extends UntypedServiceImplementation {
  /** Bidirectional streaming RPC for speech-to-speech conversion */
  streamSpeechToSpeech: handleBidiStreamingCall<SpeechToSpeechRequest, SpeechToSpeechResponse>;
}

export interface SpeechToSpeechClient extends Client {
  /** Bidirectional streaming RPC for speech-to-speech conversion */
  streamSpeechToSpeech(): ClientDuplexStream<SpeechToSpeechRequest, SpeechToSpeechResponse>;
  streamSpeechToSpeech(
    options: Partial<CallOptions>,
  ): ClientDuplexStream<SpeechToSpeechRequest, SpeechToSpeechResponse>;
  streamSpeechToSpeech(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<SpeechToSpeechRequest, SpeechToSpeechResponse>;
}

export const SpeechToSpeechClient = makeGenericClientConstructor(
  SpeechToSpeechService,
  "nvidia.ai4m.s2s.v1.SpeechToSpeech",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SpeechToSpeechClient;
  service: typeof SpeechToSpeechService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
