// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v7.35.1
// source: nvidia/ai4m/video/v1/video.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Any } from "../../../../google/protobuf/any";

export const protobufPackage = "nvidia.ai4m.video.v1";

/** Enum representing supported video codecs */
export enum VideoCodec {
  /** VIDEO_CODEC_UNSPECIFIED - Unspecified video codec */
  VIDEO_CODEC_UNSPECIFIED = 0,
  /** VIDEO_CODEC_H264 - H.264 video codec */
  VIDEO_CODEC_H264 = 1,
  UNRECOGNIZED = -1,
}

export function videoCodecFromJSON(object: any): VideoCodec {
  switch (object) {
    case 0:
    case "VIDEO_CODEC_UNSPECIFIED":
      return VideoCodec.VIDEO_CODEC_UNSPECIFIED;
    case 1:
    case "VIDEO_CODEC_H264":
      return VideoCodec.VIDEO_CODEC_H264;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VideoCodec.UNRECOGNIZED;
  }
}

export function videoCodecToJSON(object: VideoCodec): string {
  switch (object) {
    case VideoCodec.VIDEO_CODEC_UNSPECIFIED:
      return "VIDEO_CODEC_UNSPECIFIED";
    case VideoCodec.VIDEO_CODEC_H264:
      return "VIDEO_CODEC_H264";
    case VideoCodec.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Message representing information about a video */
export interface VideoConfig {
  /** The encoding format of the video */
  encoding:
    | VideoEncoding
    | undefined;
  /** Codec information */
  codec?: VideoCodec | undefined;
}

/** LossyEncoding specifies parameters for lossy video compression */
export interface LossyEncoding {
  /** Target bitrate for video encoding in mega bits per second */
  bitrate_mbps?:
    | number
    | undefined;
  /** Interval between IDR frames (keyframes) in number of frames */
  idr_interval?: number | undefined;
}

/**
 * CustomEncodingParams allows specifying custom encoding parameters
 * for Gst-nvvideo4linux2 encoder plugin
 */
export interface CustomEncodingParams {
  /**
   * Map of string key-value pairs for custom encoding configuration
   * Each value can be any protobuf message type using google.protobuf.Any
   */
  custom: { [key: string]: Any };
}

export interface CustomEncodingParams_CustomEntry {
  key: string;
  value: Any | undefined;
}

/** VideoEncoding specifies parameters for encoding video. */
export interface VideoEncoding {
  /** If true, use lossless encoding with no compression */
  lossless?:
    | boolean
    | undefined;
  /** Use lossy encoding with configurable bitrate and keyframe settings */
  lossy?:
    | LossyEncoding
    | undefined;
  /** Use custom encoding parameters specified as key-value pairs */
  custom_encoding?: CustomEncodingParams | undefined;
}

function createBaseVideoConfig(): VideoConfig {
  return { encoding: undefined, codec: undefined };
}

export const VideoConfig: MessageFns<VideoConfig> = {
  encode(message: VideoConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.encoding !== undefined) {
      VideoEncoding.encode(message.encoding, writer.uint32(10).fork()).join();
    }
    if (message.codec !== undefined) {
      writer.uint32(16).int32(message.codec);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VideoConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVideoConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.encoding = VideoEncoding.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.codec = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VideoConfig {
    return {
      encoding: isSet(object.encoding) ? VideoEncoding.fromJSON(object.encoding) : undefined,
      codec: isSet(object.codec) ? videoCodecFromJSON(object.codec) : undefined,
    };
  },

  toJSON(message: VideoConfig): unknown {
    const obj: any = {};
    if (message.encoding !== undefined) {
      obj.encoding = VideoEncoding.toJSON(message.encoding);
    }
    if (message.codec !== undefined) {
      obj.codec = videoCodecToJSON(message.codec);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VideoConfig>, I>>(base?: I): VideoConfig {
    return VideoConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VideoConfig>, I>>(object: I): VideoConfig {
    const message = createBaseVideoConfig();
    message.encoding = (object.encoding !== undefined && object.encoding !== null)
      ? VideoEncoding.fromPartial(object.encoding)
      : undefined;
    message.codec = object.codec ?? undefined;
    return message;
  },
};

function createBaseLossyEncoding(): LossyEncoding {
  return { bitrate_mbps: undefined, idr_interval: undefined };
}

export const LossyEncoding: MessageFns<LossyEncoding> = {
  encode(message: LossyEncoding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bitrate_mbps !== undefined) {
      writer.uint32(8).uint32(message.bitrate_mbps);
    }
    if (message.idr_interval !== undefined) {
      writer.uint32(16).uint32(message.idr_interval);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LossyEncoding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLossyEncoding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bitrate_mbps = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.idr_interval = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LossyEncoding {
    return {
      bitrate_mbps: isSet(object.bitrate_mbps) ? globalThis.Number(object.bitrate_mbps) : undefined,
      idr_interval: isSet(object.idr_interval) ? globalThis.Number(object.idr_interval) : undefined,
    };
  },

  toJSON(message: LossyEncoding): unknown {
    const obj: any = {};
    if (message.bitrate_mbps !== undefined) {
      obj.bitrate_mbps = Math.round(message.bitrate_mbps);
    }
    if (message.idr_interval !== undefined) {
      obj.idr_interval = Math.round(message.idr_interval);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LossyEncoding>, I>>(base?: I): LossyEncoding {
    return LossyEncoding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LossyEncoding>, I>>(object: I): LossyEncoding {
    const message = createBaseLossyEncoding();
    message.bitrate_mbps = object.bitrate_mbps ?? undefined;
    message.idr_interval = object.idr_interval ?? undefined;
    return message;
  },
};

function createBaseCustomEncodingParams(): CustomEncodingParams {
  return { custom: {} };
}

export const CustomEncodingParams: MessageFns<CustomEncodingParams> = {
  encode(message: CustomEncodingParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    Object.entries(message.custom).forEach(([key, value]) => {
      CustomEncodingParams_CustomEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CustomEncodingParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomEncodingParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = CustomEncodingParams_CustomEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.custom[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CustomEncodingParams {
    return {
      custom: isObject(object.custom)
        ? Object.entries(object.custom).reduce<{ [key: string]: Any }>((acc, [key, value]) => {
          acc[key] = Any.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: CustomEncodingParams): unknown {
    const obj: any = {};
    if (message.custom) {
      const entries = Object.entries(message.custom);
      if (entries.length > 0) {
        obj.custom = {};
        entries.forEach(([k, v]) => {
          obj.custom[k] = Any.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CustomEncodingParams>, I>>(base?: I): CustomEncodingParams {
    return CustomEncodingParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CustomEncodingParams>, I>>(object: I): CustomEncodingParams {
    const message = createBaseCustomEncodingParams();
    message.custom = Object.entries(object.custom ?? {}).reduce<{ [key: string]: Any }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = Any.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseCustomEncodingParams_CustomEntry(): CustomEncodingParams_CustomEntry {
  return { key: "", value: undefined };
}

export const CustomEncodingParams_CustomEntry: MessageFns<CustomEncodingParams_CustomEntry> = {
  encode(message: CustomEncodingParams_CustomEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Any.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CustomEncodingParams_CustomEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomEncodingParams_CustomEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CustomEncodingParams_CustomEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Any.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: CustomEncodingParams_CustomEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Any.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CustomEncodingParams_CustomEntry>, I>>(
    base?: I,
  ): CustomEncodingParams_CustomEntry {
    return CustomEncodingParams_CustomEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CustomEncodingParams_CustomEntry>, I>>(
    object: I,
  ): CustomEncodingParams_CustomEntry {
    const message = createBaseCustomEncodingParams_CustomEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Any.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseVideoEncoding(): VideoEncoding {
  return { lossless: undefined, lossy: undefined, custom_encoding: undefined };
}

export const VideoEncoding: MessageFns<VideoEncoding> = {
  encode(message: VideoEncoding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lossless !== undefined) {
      writer.uint32(8).bool(message.lossless);
    }
    if (message.lossy !== undefined) {
      LossyEncoding.encode(message.lossy, writer.uint32(18).fork()).join();
    }
    if (message.custom_encoding !== undefined) {
      CustomEncodingParams.encode(message.custom_encoding, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VideoEncoding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVideoEncoding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.lossless = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lossy = LossyEncoding.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.custom_encoding = CustomEncodingParams.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VideoEncoding {
    return {
      lossless: isSet(object.lossless) ? globalThis.Boolean(object.lossless) : undefined,
      lossy: isSet(object.lossy) ? LossyEncoding.fromJSON(object.lossy) : undefined,
      custom_encoding: isSet(object.custom_encoding)
        ? CustomEncodingParams.fromJSON(object.custom_encoding)
        : undefined,
    };
  },

  toJSON(message: VideoEncoding): unknown {
    const obj: any = {};
    if (message.lossless !== undefined) {
      obj.lossless = message.lossless;
    }
    if (message.lossy !== undefined) {
      obj.lossy = LossyEncoding.toJSON(message.lossy);
    }
    if (message.custom_encoding !== undefined) {
      obj.custom_encoding = CustomEncodingParams.toJSON(message.custom_encoding);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VideoEncoding>, I>>(base?: I): VideoEncoding {
    return VideoEncoding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VideoEncoding>, I>>(object: I): VideoEncoding {
    const message = createBaseVideoEncoding();
    message.lossless = object.lossless ?? undefined;
    message.lossy = (object.lossy !== undefined && object.lossy !== null)
      ? LossyEncoding.fromPartial(object.lossy)
      : undefined;
    message.custom_encoding = (object.custom_encoding !== undefined && object.custom_encoding !== null)
      ? CustomEncodingParams.fromPartial(object.custom_encoding)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
