// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v7.35.1
// source: nvidia/ai4m/activespeakerdetection/v1/activespeakerdetection.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../../../google/protobuf/empty";
import { AudioConfig } from "../../audio/v1/audio";
import { BoundingBox } from "../../common/v1/common";
import { VideoConfig } from "../../video/v1/video";

export const protobufPackage = "nvidia.ai4m.activespeakerdetection.v1";

/** Source of audio data for active speaker detection. */
export enum AudioSourceConfig {
  /** AUDIO_SOURCE_CONFIG_UNSPECIFIED - Unspecified; defaults to separate stream behavior. */
  AUDIO_SOURCE_CONFIG_UNSPECIFIED = 0,
  /** AUDIO_SOURCE_CONFIG_SEPARATE_STREAM - Client provides a separate audio stream alongside video. */
  AUDIO_SOURCE_CONFIG_SEPARATE_STREAM = 1,
  /** AUDIO_SOURCE_CONFIG_EMBEDDED_IN_VIDEO - Audio is demuxed from the video container (no separate audio needed). */
  AUDIO_SOURCE_CONFIG_EMBEDDED_IN_VIDEO = 2,
  UNRECOGNIZED = -1,
}

export function audioSourceConfigFromJSON(object: any): AudioSourceConfig {
  switch (object) {
    case 0:
    case "AUDIO_SOURCE_CONFIG_UNSPECIFIED":
      return AudioSourceConfig.AUDIO_SOURCE_CONFIG_UNSPECIFIED;
    case 1:
    case "AUDIO_SOURCE_CONFIG_SEPARATE_STREAM":
      return AudioSourceConfig.AUDIO_SOURCE_CONFIG_SEPARATE_STREAM;
    case 2:
    case "AUDIO_SOURCE_CONFIG_EMBEDDED_IN_VIDEO":
      return AudioSourceConfig.AUDIO_SOURCE_CONFIG_EMBEDDED_IN_VIDEO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AudioSourceConfig.UNRECOGNIZED;
  }
}

export function audioSourceConfigToJSON(object: AudioSourceConfig): string {
  switch (object) {
    case AudioSourceConfig.AUDIO_SOURCE_CONFIG_UNSPECIFIED:
      return "AUDIO_SOURCE_CONFIG_UNSPECIFIED";
    case AudioSourceConfig.AUDIO_SOURCE_CONFIG_SEPARATE_STREAM:
      return "AUDIO_SOURCE_CONFIG_SEPARATE_STREAM";
    case AudioSourceConfig.AUDIO_SOURCE_CONFIG_EMBEDDED_IN_VIDEO:
      return "AUDIO_SOURCE_CONFIG_EMBEDDED_IN_VIDEO";
    case AudioSourceConfig.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface DetectActiveSpeakerRequest {
  /** Configuration for the speaker detection */
  config?:
    | ActiveSpeakerDetectionConfig
    | undefined;
  /** Input data for the speaker detection */
  data?: ActiveSpeakerDetectionData | undefined;
}

export interface ActiveSpeakerDetectionConfig {
  /** Input audio configuration */
  input_audio_config:
    | AudioConfig
    | undefined;
  /** Input video configuration */
  input_video_config:
    | VideoConfig
    | undefined;
  /**
   * Where audio originates: separate stream or embedded in video container.
   * Defaults to AUDIO_SOURCE_CONFIG_UNSPECIFIED (treated as separate stream).
   */
  audio_source_config: AudioSourceConfig;
  /**
   * Speaker detection threshold
   * Minimum confidence score in (0, 1) to consider a face as speaking
   * Default: 0.5986
   */
  speaker_detection_threshold?: number | undefined;
}

export interface ActiveSpeakerDetectionData {
  /** Video data */
  video_data?:
    | Uint8Array
    | undefined;
  /** Audio data */
  audio_data?:
    | Uint8Array
    | undefined;
  /** Diarization information */
  diarization_info?: AudioDiarizationInfo | undefined;
}

export interface AudioDiarizationInfo {
  /** List of segment-level timing and speaker information */
  segments: AudioSegmentInfo[];
  /** Reserved for future use: Transcript of the audio */
  transcript?: string | undefined;
}

/** Timing Segment-specific information. */
export interface AudioSegmentInfo {
  /**
   * Time offset relative to the beginning of the audio in ms
   * and corresponding to the start of the segment
   */
  start_time: number;
  /**
   * Time offset relative to the beginning of the audio in ms
   * and corresponding to the end of the segment.
   */
  end_time: number;
  /**
   * A distinct integer value is assigned for every speaker within
   * the audio stream.
   */
  speaker_id: number;
  /** Reserved for future use: the word corresponding to this segment. */
  word?:
    | string
    | undefined;
  /** Reserved for future use: the language code of the word (e.g. en-US). */
  language_code?: string | undefined;
}

export interface SpeakerInfo {
  /** Bounding box corresponding to the active speaker */
  speaker_bbox:
    | BoundingBox
    | undefined;
  /**
   * Audio Track ID
   * Based on diarized data in a multi-speaker scenario
   */
  diarized_speaker_id: number;
  /**
   * Unique Face ID assigned to each face detected
   * Face IDs start from 0.
   */
  face_id: number;
  /** Flag to indicate if the speaker is speaking in this frame */
  is_speaking: boolean;
  /** Face Detection confidence score (0.0 to 1.0) */
  face_detection_confidence: number;
}

export interface DetectActiveSpeakerResponse {
  /** Echoed configuration parameters */
  config?:
    | ActiveSpeakerDetectionConfig
    | undefined;
  /** Active speaker bounding box and speaker ID */
  active_speaker_detection_result?:
    | ActiveSpeakerDetectionResult
    | undefined;
  /** Empty message used to maintain connection */
  keepalive?: Empty | undefined;
}

export interface ActiveSpeakerDetectionResult {
  /** Frame ID */
  frame_id: number;
  /** Detected Speaker Info per frame */
  speaker_data: SpeakerInfo[];
}

function createBaseDetectActiveSpeakerRequest(): DetectActiveSpeakerRequest {
  return { config: undefined, data: undefined };
}

export const DetectActiveSpeakerRequest: MessageFns<DetectActiveSpeakerRequest> = {
  encode(message: DetectActiveSpeakerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      ActiveSpeakerDetectionConfig.encode(message.config, writer.uint32(10).fork()).join();
    }
    if (message.data !== undefined) {
      ActiveSpeakerDetectionData.encode(message.data, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectActiveSpeakerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectActiveSpeakerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = ActiveSpeakerDetectionConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = ActiveSpeakerDetectionData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectActiveSpeakerRequest {
    return {
      config: isSet(object.config) ? ActiveSpeakerDetectionConfig.fromJSON(object.config) : undefined,
      data: isSet(object.data) ? ActiveSpeakerDetectionData.fromJSON(object.data) : undefined,
    };
  },

  toJSON(message: DetectActiveSpeakerRequest): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = ActiveSpeakerDetectionConfig.toJSON(message.config);
    }
    if (message.data !== undefined) {
      obj.data = ActiveSpeakerDetectionData.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectActiveSpeakerRequest>, I>>(base?: I): DetectActiveSpeakerRequest {
    return DetectActiveSpeakerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectActiveSpeakerRequest>, I>>(object: I): DetectActiveSpeakerRequest {
    const message = createBaseDetectActiveSpeakerRequest();
    message.config = (object.config !== undefined && object.config !== null)
      ? ActiveSpeakerDetectionConfig.fromPartial(object.config)
      : undefined;
    message.data = (object.data !== undefined && object.data !== null)
      ? ActiveSpeakerDetectionData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseActiveSpeakerDetectionConfig(): ActiveSpeakerDetectionConfig {
  return {
    input_audio_config: undefined,
    input_video_config: undefined,
    audio_source_config: 0,
    speaker_detection_threshold: undefined,
  };
}

export const ActiveSpeakerDetectionConfig: MessageFns<ActiveSpeakerDetectionConfig> = {
  encode(message: ActiveSpeakerDetectionConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.input_audio_config !== undefined) {
      AudioConfig.encode(message.input_audio_config, writer.uint32(10).fork()).join();
    }
    if (message.input_video_config !== undefined) {
      VideoConfig.encode(message.input_video_config, writer.uint32(18).fork()).join();
    }
    if (message.audio_source_config !== 0) {
      writer.uint32(24).int32(message.audio_source_config);
    }
    if (message.speaker_detection_threshold !== undefined) {
      writer.uint32(37).float(message.speaker_detection_threshold);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActiveSpeakerDetectionConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActiveSpeakerDetectionConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.input_audio_config = AudioConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input_video_config = VideoConfig.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.audio_source_config = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.speaker_detection_threshold = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActiveSpeakerDetectionConfig {
    return {
      input_audio_config: isSet(object.input_audio_config)
        ? AudioConfig.fromJSON(object.input_audio_config)
        : undefined,
      input_video_config: isSet(object.input_video_config)
        ? VideoConfig.fromJSON(object.input_video_config)
        : undefined,
      audio_source_config: isSet(object.audio_source_config)
        ? audioSourceConfigFromJSON(object.audio_source_config)
        : 0,
      speaker_detection_threshold: isSet(object.speaker_detection_threshold)
        ? globalThis.Number(object.speaker_detection_threshold)
        : undefined,
    };
  },

  toJSON(message: ActiveSpeakerDetectionConfig): unknown {
    const obj: any = {};
    if (message.input_audio_config !== undefined) {
      obj.input_audio_config = AudioConfig.toJSON(message.input_audio_config);
    }
    if (message.input_video_config !== undefined) {
      obj.input_video_config = VideoConfig.toJSON(message.input_video_config);
    }
    if (message.audio_source_config !== 0) {
      obj.audio_source_config = audioSourceConfigToJSON(message.audio_source_config);
    }
    if (message.speaker_detection_threshold !== undefined) {
      obj.speaker_detection_threshold = message.speaker_detection_threshold;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActiveSpeakerDetectionConfig>, I>>(base?: I): ActiveSpeakerDetectionConfig {
    return ActiveSpeakerDetectionConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActiveSpeakerDetectionConfig>, I>>(object: I): ActiveSpeakerDetectionConfig {
    const message = createBaseActiveSpeakerDetectionConfig();
    message.input_audio_config = (object.input_audio_config !== undefined && object.input_audio_config !== null)
      ? AudioConfig.fromPartial(object.input_audio_config)
      : undefined;
    message.input_video_config = (object.input_video_config !== undefined && object.input_video_config !== null)
      ? VideoConfig.fromPartial(object.input_video_config)
      : undefined;
    message.audio_source_config = object.audio_source_config ?? 0;
    message.speaker_detection_threshold = object.speaker_detection_threshold ?? undefined;
    return message;
  },
};

function createBaseActiveSpeakerDetectionData(): ActiveSpeakerDetectionData {
  return { video_data: undefined, audio_data: undefined, diarization_info: undefined };
}

export const ActiveSpeakerDetectionData: MessageFns<ActiveSpeakerDetectionData> = {
  encode(message: ActiveSpeakerDetectionData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.video_data !== undefined) {
      writer.uint32(10).bytes(message.video_data);
    }
    if (message.audio_data !== undefined) {
      writer.uint32(18).bytes(message.audio_data);
    }
    if (message.diarization_info !== undefined) {
      AudioDiarizationInfo.encode(message.diarization_info, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActiveSpeakerDetectionData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActiveSpeakerDetectionData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.video_data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.audio_data = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.diarization_info = AudioDiarizationInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActiveSpeakerDetectionData {
    return {
      video_data: isSet(object.video_data) ? bytesFromBase64(object.video_data) : undefined,
      audio_data: isSet(object.audio_data) ? bytesFromBase64(object.audio_data) : undefined,
      diarization_info: isSet(object.diarization_info)
        ? AudioDiarizationInfo.fromJSON(object.diarization_info)
        : undefined,
    };
  },

  toJSON(message: ActiveSpeakerDetectionData): unknown {
    const obj: any = {};
    if (message.video_data !== undefined) {
      obj.video_data = base64FromBytes(message.video_data);
    }
    if (message.audio_data !== undefined) {
      obj.audio_data = base64FromBytes(message.audio_data);
    }
    if (message.diarization_info !== undefined) {
      obj.diarization_info = AudioDiarizationInfo.toJSON(message.diarization_info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActiveSpeakerDetectionData>, I>>(base?: I): ActiveSpeakerDetectionData {
    return ActiveSpeakerDetectionData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActiveSpeakerDetectionData>, I>>(object: I): ActiveSpeakerDetectionData {
    const message = createBaseActiveSpeakerDetectionData();
    message.video_data = object.video_data ?? undefined;
    message.audio_data = object.audio_data ?? undefined;
    message.diarization_info = (object.diarization_info !== undefined && object.diarization_info !== null)
      ? AudioDiarizationInfo.fromPartial(object.diarization_info)
      : undefined;
    return message;
  },
};

function createBaseAudioDiarizationInfo(): AudioDiarizationInfo {
  return { segments: [], transcript: undefined };
}

export const AudioDiarizationInfo: MessageFns<AudioDiarizationInfo> = {
  encode(message: AudioDiarizationInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.segments) {
      AudioSegmentInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.transcript !== undefined) {
      writer.uint32(18).string(message.transcript);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioDiarizationInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioDiarizationInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.segments.push(AudioSegmentInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transcript = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AudioDiarizationInfo {
    return {
      segments: globalThis.Array.isArray(object?.segments)
        ? object.segments.map((e: any) => AudioSegmentInfo.fromJSON(e))
        : [],
      transcript: isSet(object.transcript) ? globalThis.String(object.transcript) : undefined,
    };
  },

  toJSON(message: AudioDiarizationInfo): unknown {
    const obj: any = {};
    if (message.segments?.length) {
      obj.segments = message.segments.map((e) => AudioSegmentInfo.toJSON(e));
    }
    if (message.transcript !== undefined) {
      obj.transcript = message.transcript;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioDiarizationInfo>, I>>(base?: I): AudioDiarizationInfo {
    return AudioDiarizationInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioDiarizationInfo>, I>>(object: I): AudioDiarizationInfo {
    const message = createBaseAudioDiarizationInfo();
    message.segments = object.segments?.map((e) => AudioSegmentInfo.fromPartial(e)) || [];
    message.transcript = object.transcript ?? undefined;
    return message;
  },
};

function createBaseAudioSegmentInfo(): AudioSegmentInfo {
  return { start_time: 0, end_time: 0, speaker_id: 0, word: undefined, language_code: undefined };
}

export const AudioSegmentInfo: MessageFns<AudioSegmentInfo> = {
  encode(message: AudioSegmentInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.start_time !== 0) {
      writer.uint32(8).uint32(message.start_time);
    }
    if (message.end_time !== 0) {
      writer.uint32(16).uint32(message.end_time);
    }
    if (message.speaker_id !== 0) {
      writer.uint32(24).int32(message.speaker_id);
    }
    if (message.word !== undefined) {
      writer.uint32(34).string(message.word);
    }
    if (message.language_code !== undefined) {
      writer.uint32(42).string(message.language_code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioSegmentInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioSegmentInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.start_time = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.end_time = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.speaker_id = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.word = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.language_code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AudioSegmentInfo {
    return {
      start_time: isSet(object.start_time) ? globalThis.Number(object.start_time) : 0,
      end_time: isSet(object.end_time) ? globalThis.Number(object.end_time) : 0,
      speaker_id: isSet(object.speaker_id) ? globalThis.Number(object.speaker_id) : 0,
      word: isSet(object.word) ? globalThis.String(object.word) : undefined,
      language_code: isSet(object.language_code) ? globalThis.String(object.language_code) : undefined,
    };
  },

  toJSON(message: AudioSegmentInfo): unknown {
    const obj: any = {};
    if (message.start_time !== 0) {
      obj.start_time = Math.round(message.start_time);
    }
    if (message.end_time !== 0) {
      obj.end_time = Math.round(message.end_time);
    }
    if (message.speaker_id !== 0) {
      obj.speaker_id = Math.round(message.speaker_id);
    }
    if (message.word !== undefined) {
      obj.word = message.word;
    }
    if (message.language_code !== undefined) {
      obj.language_code = message.language_code;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioSegmentInfo>, I>>(base?: I): AudioSegmentInfo {
    return AudioSegmentInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioSegmentInfo>, I>>(object: I): AudioSegmentInfo {
    const message = createBaseAudioSegmentInfo();
    message.start_time = object.start_time ?? 0;
    message.end_time = object.end_time ?? 0;
    message.speaker_id = object.speaker_id ?? 0;
    message.word = object.word ?? undefined;
    message.language_code = object.language_code ?? undefined;
    return message;
  },
};

function createBaseSpeakerInfo(): SpeakerInfo {
  return {
    speaker_bbox: undefined,
    diarized_speaker_id: 0,
    face_id: 0,
    is_speaking: false,
    face_detection_confidence: 0,
  };
}

export const SpeakerInfo: MessageFns<SpeakerInfo> = {
  encode(message: SpeakerInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.speaker_bbox !== undefined) {
      BoundingBox.encode(message.speaker_bbox, writer.uint32(10).fork()).join();
    }
    if (message.diarized_speaker_id !== 0) {
      writer.uint32(16).int32(message.diarized_speaker_id);
    }
    if (message.face_id !== 0) {
      writer.uint32(24).int32(message.face_id);
    }
    if (message.is_speaking !== false) {
      writer.uint32(32).bool(message.is_speaking);
    }
    if (message.face_detection_confidence !== 0) {
      writer.uint32(45).float(message.face_detection_confidence);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeakerInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeakerInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.speaker_bbox = BoundingBox.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.diarized_speaker_id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.face_id = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.is_speaking = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.face_detection_confidence = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeakerInfo {
    return {
      speaker_bbox: isSet(object.speaker_bbox) ? BoundingBox.fromJSON(object.speaker_bbox) : undefined,
      diarized_speaker_id: isSet(object.diarized_speaker_id) ? globalThis.Number(object.diarized_speaker_id) : 0,
      face_id: isSet(object.face_id) ? globalThis.Number(object.face_id) : 0,
      is_speaking: isSet(object.is_speaking) ? globalThis.Boolean(object.is_speaking) : false,
      face_detection_confidence: isSet(object.face_detection_confidence)
        ? globalThis.Number(object.face_detection_confidence)
        : 0,
    };
  },

  toJSON(message: SpeakerInfo): unknown {
    const obj: any = {};
    if (message.speaker_bbox !== undefined) {
      obj.speaker_bbox = BoundingBox.toJSON(message.speaker_bbox);
    }
    if (message.diarized_speaker_id !== 0) {
      obj.diarized_speaker_id = Math.round(message.diarized_speaker_id);
    }
    if (message.face_id !== 0) {
      obj.face_id = Math.round(message.face_id);
    }
    if (message.is_speaking !== false) {
      obj.is_speaking = message.is_speaking;
    }
    if (message.face_detection_confidence !== 0) {
      obj.face_detection_confidence = message.face_detection_confidence;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeakerInfo>, I>>(base?: I): SpeakerInfo {
    return SpeakerInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeakerInfo>, I>>(object: I): SpeakerInfo {
    const message = createBaseSpeakerInfo();
    message.speaker_bbox = (object.speaker_bbox !== undefined && object.speaker_bbox !== null)
      ? BoundingBox.fromPartial(object.speaker_bbox)
      : undefined;
    message.diarized_speaker_id = object.diarized_speaker_id ?? 0;
    message.face_id = object.face_id ?? 0;
    message.is_speaking = object.is_speaking ?? false;
    message.face_detection_confidence = object.face_detection_confidence ?? 0;
    return message;
  },
};

function createBaseDetectActiveSpeakerResponse(): DetectActiveSpeakerResponse {
  return { config: undefined, active_speaker_detection_result: undefined, keepalive: undefined };
}

export const DetectActiveSpeakerResponse: MessageFns<DetectActiveSpeakerResponse> = {
  encode(message: DetectActiveSpeakerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      ActiveSpeakerDetectionConfig.encode(message.config, writer.uint32(10).fork()).join();
    }
    if (message.active_speaker_detection_result !== undefined) {
      ActiveSpeakerDetectionResult.encode(message.active_speaker_detection_result, writer.uint32(18).fork()).join();
    }
    if (message.keepalive !== undefined) {
      Empty.encode(message.keepalive, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectActiveSpeakerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectActiveSpeakerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = ActiveSpeakerDetectionConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.active_speaker_detection_result = ActiveSpeakerDetectionResult.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.keepalive = Empty.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectActiveSpeakerResponse {
    return {
      config: isSet(object.config) ? ActiveSpeakerDetectionConfig.fromJSON(object.config) : undefined,
      active_speaker_detection_result: isSet(object.active_speaker_detection_result)
        ? ActiveSpeakerDetectionResult.fromJSON(object.active_speaker_detection_result)
        : undefined,
      keepalive: isSet(object.keepalive) ? Empty.fromJSON(object.keepalive) : undefined,
    };
  },

  toJSON(message: DetectActiveSpeakerResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = ActiveSpeakerDetectionConfig.toJSON(message.config);
    }
    if (message.active_speaker_detection_result !== undefined) {
      obj.active_speaker_detection_result = ActiveSpeakerDetectionResult.toJSON(
        message.active_speaker_detection_result,
      );
    }
    if (message.keepalive !== undefined) {
      obj.keepalive = Empty.toJSON(message.keepalive);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectActiveSpeakerResponse>, I>>(base?: I): DetectActiveSpeakerResponse {
    return DetectActiveSpeakerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectActiveSpeakerResponse>, I>>(object: I): DetectActiveSpeakerResponse {
    const message = createBaseDetectActiveSpeakerResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? ActiveSpeakerDetectionConfig.fromPartial(object.config)
      : undefined;
    message.active_speaker_detection_result =
      (object.active_speaker_detection_result !== undefined && object.active_speaker_detection_result !== null)
        ? ActiveSpeakerDetectionResult.fromPartial(object.active_speaker_detection_result)
        : undefined;
    message.keepalive = (object.keepalive !== undefined && object.keepalive !== null)
      ? Empty.fromPartial(object.keepalive)
      : undefined;
    return message;
  },
};

function createBaseActiveSpeakerDetectionResult(): ActiveSpeakerDetectionResult {
  return { frame_id: 0, speaker_data: [] };
}

export const ActiveSpeakerDetectionResult: MessageFns<ActiveSpeakerDetectionResult> = {
  encode(message: ActiveSpeakerDetectionResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frame_id !== 0) {
      writer.uint32(8).uint32(message.frame_id);
    }
    for (const v of message.speaker_data) {
      SpeakerInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActiveSpeakerDetectionResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActiveSpeakerDetectionResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.frame_id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.speaker_data.push(SpeakerInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActiveSpeakerDetectionResult {
    return {
      frame_id: isSet(object.frame_id) ? globalThis.Number(object.frame_id) : 0,
      speaker_data: globalThis.Array.isArray(object?.speaker_data)
        ? object.speaker_data.map((e: any) => SpeakerInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ActiveSpeakerDetectionResult): unknown {
    const obj: any = {};
    if (message.frame_id !== 0) {
      obj.frame_id = Math.round(message.frame_id);
    }
    if (message.speaker_data?.length) {
      obj.speaker_data = message.speaker_data.map((e) => SpeakerInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActiveSpeakerDetectionResult>, I>>(base?: I): ActiveSpeakerDetectionResult {
    return ActiveSpeakerDetectionResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActiveSpeakerDetectionResult>, I>>(object: I): ActiveSpeakerDetectionResult {
    const message = createBaseActiveSpeakerDetectionResult();
    message.frame_id = object.frame_id ?? 0;
    message.speaker_data = object.speaker_data?.map((e) => SpeakerInfo.fromPartial(e)) || [];
    return message;
  },
};

export type ActiveSpeakerDetectionServiceService = typeof ActiveSpeakerDetectionServiceService;
export const ActiveSpeakerDetectionServiceService = {
  /**
   * DetectActiveSpeaker is a bidirectional streaming RPC that takes audio file,
   * video file and diarization file as inputs and returns a bounding box
   * corresponding to the active speaker and its speaker tag for each frame.
   * request: Stream of DetectActiveSpeakerRequest messages containing
   * either configuration or input data
   * response: Stream of DetectActiveSpeakerResponse messages
   * containing either configuration, bounding box
   * and speaker tag for each frame, or keepalive
   */
  detectActiveSpeaker: {
    path: "/nvidia.ai4m.activespeakerdetection.v1.ActiveSpeakerDetectionService/DetectActiveSpeaker",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: DetectActiveSpeakerRequest): Buffer =>
      Buffer.from(DetectActiveSpeakerRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DetectActiveSpeakerRequest => DetectActiveSpeakerRequest.decode(value),
    responseSerialize: (value: DetectActiveSpeakerResponse): Buffer =>
      Buffer.from(DetectActiveSpeakerResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DetectActiveSpeakerResponse => DetectActiveSpeakerResponse.decode(value),
  },
} as const;

export interface ActiveSpeakerDetectionServiceServer extends UntypedServiceImplementation {
  /**
   * DetectActiveSpeaker is a bidirectional streaming RPC that takes audio file,
   * video file and diarization file as inputs and returns a bounding box
   * corresponding to the active speaker and its speaker tag for each frame.
   * request: Stream of DetectActiveSpeakerRequest messages containing
   * either configuration or input data
   * response: Stream of DetectActiveSpeakerResponse messages
   * containing either configuration, bounding box
   * and speaker tag for each frame, or keepalive
   */
  detectActiveSpeaker: handleBidiStreamingCall<DetectActiveSpeakerRequest, DetectActiveSpeakerResponse>;
}

export interface ActiveSpeakerDetectionServiceClient extends Client {
  /**
   * DetectActiveSpeaker is a bidirectional streaming RPC that takes audio file,
   * video file and diarization file as inputs and returns a bounding box
   * corresponding to the active speaker and its speaker tag for each frame.
   * request: Stream of DetectActiveSpeakerRequest messages containing
   * either configuration or input data
   * response: Stream of DetectActiveSpeakerResponse messages
   * containing either configuration, bounding box
   * and speaker tag for each frame, or keepalive
   */
  detectActiveSpeaker(): ClientDuplexStream<DetectActiveSpeakerRequest, DetectActiveSpeakerResponse>;
  detectActiveSpeaker(
    options: Partial<CallOptions>,
  ): ClientDuplexStream<DetectActiveSpeakerRequest, DetectActiveSpeakerResponse>;
  detectActiveSpeaker(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<DetectActiveSpeakerRequest, DetectActiveSpeakerResponse>;
}

export const ActiveSpeakerDetectionServiceClient = makeGenericClientConstructor(
  ActiveSpeakerDetectionServiceService,
  "nvidia.ai4m.activespeakerdetection.v1.ActiveSpeakerDetectionService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): ActiveSpeakerDetectionServiceClient;
  service: typeof ActiveSpeakerDetectionServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
