// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v7.35.1
// source: nvidia/ai4m/controller/v1/controller.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../../../google/protobuf/empty";
import {
  ActiveSpeakerDetectionConfig,
  AudioDiarizationInfo,
} from "../../activespeakerdetection/v1/activespeakerdetection";
import { AudioConfig } from "../../audio/v1/audio";
import { LipsyncConfig } from "../../lipsync/v1/lipsync";
import { SpeechToSpeechConfig } from "../../s2s/v1/s2s";

export const protobufPackage = "nvidia.ai4m.controller.v1";

/** Controller-level configuration sent once at the start of the request stream */
export interface ContentLocalizationConfig {
  /**
   * When true, skip S2S and use translated_audio_data for LipSync input.
   * Requires at least one translated_audio_data message in the stream;
   * conversely, translated_audio_data is rejected when this flag is false.
   */
  bypass_s2s: boolean;
  /**
   * When true, skip ASD — LipSync uses internal face detection.
   * When false and ASD is configured, an asd_config message is required.
   */
  bypass_asd: boolean;
  /**
   * Properties of the original audio stream (audio_data messages).
   * The codec declared here labels the audio sent to the S2S backend.
   * When omitted, the input is treated as WAV.
   */
  input_audio_config: AudioConfig | undefined;
}

/**
 * Content localization request stream message.
 *
 * Configuration messages (controller_config, then the per-service configs)
 * are sent at the start of the stream, before any data payloads. Each
 * message carries exactly one payload; request_id may accompany any payload.
 */
export interface ContentLocalizationRequest {
  /**
   * Client-supplied correlation id echoed in responses. The server
   * generates an id when the client does not provide one.
   */
  request_id?:
    | string
    | undefined;
  /** Raw audio data */
  audio_data?:
    | Uint8Array
    | undefined;
  /** Raw video data */
  video_file_data?:
    | Uint8Array
    | undefined;
  /** S2S config */
  s2s_config?:
    | SpeechToSpeechConfig
    | undefined;
  /** Diarization info for active speaker detection */
  diarization_info?:
    | AudioDiarizationInfo
    | undefined;
  /** ASD config for active speaker detection service */
  asd_config?:
    | ActiveSpeakerDetectionConfig
    | undefined;
  /** LipSync config for lip sync service */
  lipsync_config?:
    | LipsyncConfig
    | undefined;
  /** Background audio data bytes for LipSync background audio mixing */
  background_audio_data?:
    | Uint8Array
    | undefined;
  /**
   * Pre-translated audio consumed instead of S2S output. Only valid when
   * controller_config.bypass_s2s is true.
   */
  translated_audio_data?:
    | Uint8Array
    | undefined;
  /** Controller-level config (bypass flags, input audio properties) */
  controller_config?: ContentLocalizationConfig | undefined;
}

/** Content localization response stream message. */
export interface ContentLocalizationResponse {
  /**
   * Correlation id: the client-supplied request_id when one was provided,
   * otherwise a server-generated id.
   */
  request_id?:
    | string
    | undefined;
  /** Processed video data from LipSync service */
  video_file_data?:
    | Uint8Array
    | undefined;
  /** Empty message used to maintain connection */
  keepalive?: Empty | undefined;
}

function createBaseContentLocalizationConfig(): ContentLocalizationConfig {
  return { bypass_s2s: false, bypass_asd: false, input_audio_config: undefined };
}

export const ContentLocalizationConfig: MessageFns<ContentLocalizationConfig> = {
  encode(message: ContentLocalizationConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bypass_s2s !== false) {
      writer.uint32(8).bool(message.bypass_s2s);
    }
    if (message.bypass_asd !== false) {
      writer.uint32(16).bool(message.bypass_asd);
    }
    if (message.input_audio_config !== undefined) {
      AudioConfig.encode(message.input_audio_config, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ContentLocalizationConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContentLocalizationConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bypass_s2s = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bypass_asd = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.input_audio_config = AudioConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ContentLocalizationConfig {
    return {
      bypass_s2s: isSet(object.bypass_s2s) ? globalThis.Boolean(object.bypass_s2s) : false,
      bypass_asd: isSet(object.bypass_asd) ? globalThis.Boolean(object.bypass_asd) : false,
      input_audio_config: isSet(object.input_audio_config)
        ? AudioConfig.fromJSON(object.input_audio_config)
        : undefined,
    };
  },

  toJSON(message: ContentLocalizationConfig): unknown {
    const obj: any = {};
    if (message.bypass_s2s !== false) {
      obj.bypass_s2s = message.bypass_s2s;
    }
    if (message.bypass_asd !== false) {
      obj.bypass_asd = message.bypass_asd;
    }
    if (message.input_audio_config !== undefined) {
      obj.input_audio_config = AudioConfig.toJSON(message.input_audio_config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ContentLocalizationConfig>, I>>(base?: I): ContentLocalizationConfig {
    return ContentLocalizationConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ContentLocalizationConfig>, I>>(object: I): ContentLocalizationConfig {
    const message = createBaseContentLocalizationConfig();
    message.bypass_s2s = object.bypass_s2s ?? false;
    message.bypass_asd = object.bypass_asd ?? false;
    message.input_audio_config = (object.input_audio_config !== undefined && object.input_audio_config !== null)
      ? AudioConfig.fromPartial(object.input_audio_config)
      : undefined;
    return message;
  },
};

function createBaseContentLocalizationRequest(): ContentLocalizationRequest {
  return {
    request_id: undefined,
    audio_data: undefined,
    video_file_data: undefined,
    s2s_config: undefined,
    diarization_info: undefined,
    asd_config: undefined,
    lipsync_config: undefined,
    background_audio_data: undefined,
    translated_audio_data: undefined,
    controller_config: undefined,
  };
}

export const ContentLocalizationRequest: MessageFns<ContentLocalizationRequest> = {
  encode(message: ContentLocalizationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.request_id !== undefined) {
      writer.uint32(26).string(message.request_id);
    }
    if (message.audio_data !== undefined) {
      writer.uint32(10).bytes(message.audio_data);
    }
    if (message.video_file_data !== undefined) {
      writer.uint32(18).bytes(message.video_file_data);
    }
    if (message.s2s_config !== undefined) {
      SpeechToSpeechConfig.encode(message.s2s_config, writer.uint32(34).fork()).join();
    }
    if (message.diarization_info !== undefined) {
      AudioDiarizationInfo.encode(message.diarization_info, writer.uint32(42).fork()).join();
    }
    if (message.asd_config !== undefined) {
      ActiveSpeakerDetectionConfig.encode(message.asd_config, writer.uint32(50).fork()).join();
    }
    if (message.lipsync_config !== undefined) {
      LipsyncConfig.encode(message.lipsync_config, writer.uint32(58).fork()).join();
    }
    if (message.background_audio_data !== undefined) {
      writer.uint32(66).bytes(message.background_audio_data);
    }
    if (message.translated_audio_data !== undefined) {
      writer.uint32(74).bytes(message.translated_audio_data);
    }
    if (message.controller_config !== undefined) {
      ContentLocalizationConfig.encode(message.controller_config, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ContentLocalizationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContentLocalizationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.request_id = reader.string();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audio_data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.video_file_data = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.s2s_config = SpeechToSpeechConfig.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.diarization_info = AudioDiarizationInfo.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.asd_config = ActiveSpeakerDetectionConfig.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.lipsync_config = LipsyncConfig.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.background_audio_data = reader.bytes();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.translated_audio_data = reader.bytes();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.controller_config = ContentLocalizationConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ContentLocalizationRequest {
    return {
      request_id: isSet(object.request_id) ? globalThis.String(object.request_id) : undefined,
      audio_data: isSet(object.audio_data) ? bytesFromBase64(object.audio_data) : undefined,
      video_file_data: isSet(object.video_file_data) ? bytesFromBase64(object.video_file_data) : undefined,
      s2s_config: isSet(object.s2s_config) ? SpeechToSpeechConfig.fromJSON(object.s2s_config) : undefined,
      diarization_info: isSet(object.diarization_info)
        ? AudioDiarizationInfo.fromJSON(object.diarization_info)
        : undefined,
      asd_config: isSet(object.asd_config) ? ActiveSpeakerDetectionConfig.fromJSON(object.asd_config) : undefined,
      lipsync_config: isSet(object.lipsync_config) ? LipsyncConfig.fromJSON(object.lipsync_config) : undefined,
      background_audio_data: isSet(object.background_audio_data)
        ? bytesFromBase64(object.background_audio_data)
        : undefined,
      translated_audio_data: isSet(object.translated_audio_data)
        ? bytesFromBase64(object.translated_audio_data)
        : undefined,
      controller_config: isSet(object.controller_config)
        ? ContentLocalizationConfig.fromJSON(object.controller_config)
        : undefined,
    };
  },

  toJSON(message: ContentLocalizationRequest): unknown {
    const obj: any = {};
    if (message.request_id !== undefined) {
      obj.request_id = message.request_id;
    }
    if (message.audio_data !== undefined) {
      obj.audio_data = base64FromBytes(message.audio_data);
    }
    if (message.video_file_data !== undefined) {
      obj.video_file_data = base64FromBytes(message.video_file_data);
    }
    if (message.s2s_config !== undefined) {
      obj.s2s_config = SpeechToSpeechConfig.toJSON(message.s2s_config);
    }
    if (message.diarization_info !== undefined) {
      obj.diarization_info = AudioDiarizationInfo.toJSON(message.diarization_info);
    }
    if (message.asd_config !== undefined) {
      obj.asd_config = ActiveSpeakerDetectionConfig.toJSON(message.asd_config);
    }
    if (message.lipsync_config !== undefined) {
      obj.lipsync_config = LipsyncConfig.toJSON(message.lipsync_config);
    }
    if (message.background_audio_data !== undefined) {
      obj.background_audio_data = base64FromBytes(message.background_audio_data);
    }
    if (message.translated_audio_data !== undefined) {
      obj.translated_audio_data = base64FromBytes(message.translated_audio_data);
    }
    if (message.controller_config !== undefined) {
      obj.controller_config = ContentLocalizationConfig.toJSON(message.controller_config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ContentLocalizationRequest>, I>>(base?: I): ContentLocalizationRequest {
    return ContentLocalizationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ContentLocalizationRequest>, I>>(object: I): ContentLocalizationRequest {
    const message = createBaseContentLocalizationRequest();
    message.request_id = object.request_id ?? undefined;
    message.audio_data = object.audio_data ?? undefined;
    message.video_file_data = object.video_file_data ?? undefined;
    message.s2s_config = (object.s2s_config !== undefined && object.s2s_config !== null)
      ? SpeechToSpeechConfig.fromPartial(object.s2s_config)
      : undefined;
    message.diarization_info = (object.diarization_info !== undefined && object.diarization_info !== null)
      ? AudioDiarizationInfo.fromPartial(object.diarization_info)
      : undefined;
    message.asd_config = (object.asd_config !== undefined && object.asd_config !== null)
      ? ActiveSpeakerDetectionConfig.fromPartial(object.asd_config)
      : undefined;
    message.lipsync_config = (object.lipsync_config !== undefined && object.lipsync_config !== null)
      ? LipsyncConfig.fromPartial(object.lipsync_config)
      : undefined;
    message.background_audio_data = object.background_audio_data ?? undefined;
    message.translated_audio_data = object.translated_audio_data ?? undefined;
    message.controller_config = (object.controller_config !== undefined && object.controller_config !== null)
      ? ContentLocalizationConfig.fromPartial(object.controller_config)
      : undefined;
    return message;
  },
};

function createBaseContentLocalizationResponse(): ContentLocalizationResponse {
  return { request_id: undefined, video_file_data: undefined, keepalive: undefined };
}

export const ContentLocalizationResponse: MessageFns<ContentLocalizationResponse> = {
  encode(message: ContentLocalizationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.request_id !== undefined) {
      writer.uint32(18).string(message.request_id);
    }
    if (message.video_file_data !== undefined) {
      writer.uint32(10).bytes(message.video_file_data);
    }
    if (message.keepalive !== undefined) {
      Empty.encode(message.keepalive, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ContentLocalizationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContentLocalizationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.request_id = reader.string();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.video_file_data = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.keepalive = Empty.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ContentLocalizationResponse {
    return {
      request_id: isSet(object.request_id) ? globalThis.String(object.request_id) : undefined,
      video_file_data: isSet(object.video_file_data) ? bytesFromBase64(object.video_file_data) : undefined,
      keepalive: isSet(object.keepalive) ? Empty.fromJSON(object.keepalive) : undefined,
    };
  },

  toJSON(message: ContentLocalizationResponse): unknown {
    const obj: any = {};
    if (message.request_id !== undefined) {
      obj.request_id = message.request_id;
    }
    if (message.video_file_data !== undefined) {
      obj.video_file_data = base64FromBytes(message.video_file_data);
    }
    if (message.keepalive !== undefined) {
      obj.keepalive = Empty.toJSON(message.keepalive);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ContentLocalizationResponse>, I>>(base?: I): ContentLocalizationResponse {
    return ContentLocalizationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ContentLocalizationResponse>, I>>(object: I): ContentLocalizationResponse {
    const message = createBaseContentLocalizationResponse();
    message.request_id = object.request_id ?? undefined;
    message.video_file_data = object.video_file_data ?? undefined;
    message.keepalive = (object.keepalive !== undefined && object.keepalive !== null)
      ? Empty.fromPartial(object.keepalive)
      : undefined;
    return message;
  },
};

/** Content Localization service definition */
export type ContentLocalizationControllerService = typeof ContentLocalizationControllerService;
export const ContentLocalizationControllerService = {
  /** Bidirectional streaming RPC for content localization */
  streamContentLocalization: {
    path: "/nvidia.ai4m.controller.v1.ContentLocalizationController/StreamContentLocalization",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: ContentLocalizationRequest): Buffer =>
      Buffer.from(ContentLocalizationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ContentLocalizationRequest => ContentLocalizationRequest.decode(value),
    responseSerialize: (value: ContentLocalizationResponse): Buffer =>
      Buffer.from(ContentLocalizationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ContentLocalizationResponse => ContentLocalizationResponse.decode(value),
  },
} as const;

export interface ContentLocalizationControllerServer extends UntypedServiceImplementation {
  /** Bidirectional streaming RPC for content localization */
  streamContentLocalization: handleBidiStreamingCall<ContentLocalizationRequest, ContentLocalizationResponse>;
}

export interface ContentLocalizationControllerClient extends Client {
  /** Bidirectional streaming RPC for content localization */
  streamContentLocalization(): ClientDuplexStream<ContentLocalizationRequest, ContentLocalizationResponse>;
  streamContentLocalization(
    options: Partial<CallOptions>,
  ): ClientDuplexStream<ContentLocalizationRequest, ContentLocalizationResponse>;
  streamContentLocalization(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<ContentLocalizationRequest, ContentLocalizationResponse>;
}

export const ContentLocalizationControllerClient = makeGenericClientConstructor(
  ContentLocalizationControllerService,
  "nvidia.ai4m.controller.v1.ContentLocalizationController",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): ContentLocalizationControllerClient;
  service: typeof ContentLocalizationControllerService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
