// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v7.35.1
// source: nvidia/ai4m/audio/v1/audio.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "nvidia.ai4m.audio.v1";

/** Enum representing supported audio codecs */
export enum AudioCodec {
  /** AUDIO_CODEC_UNSPECIFIED - Audio codec not specified */
  AUDIO_CODEC_UNSPECIFIED = 0,
  /** AUDIO_CODEC_MP3 - MP3 codec */
  AUDIO_CODEC_MP3 = 1,
  /** AUDIO_CODEC_WAV - WAV codec */
  AUDIO_CODEC_WAV = 2,
  /** AUDIO_CODEC_OPUS - OPUS codec */
  AUDIO_CODEC_OPUS = 3,
  UNRECOGNIZED = -1,
}

export function audioCodecFromJSON(object: any): AudioCodec {
  switch (object) {
    case 0:
    case "AUDIO_CODEC_UNSPECIFIED":
      return AudioCodec.AUDIO_CODEC_UNSPECIFIED;
    case 1:
    case "AUDIO_CODEC_MP3":
      return AudioCodec.AUDIO_CODEC_MP3;
    case 2:
    case "AUDIO_CODEC_WAV":
      return AudioCodec.AUDIO_CODEC_WAV;
    case 3:
    case "AUDIO_CODEC_OPUS":
      return AudioCodec.AUDIO_CODEC_OPUS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AudioCodec.UNRECOGNIZED;
  }
}

export function audioCodecToJSON(object: AudioCodec): string {
  switch (object) {
    case AudioCodec.AUDIO_CODEC_UNSPECIFIED:
      return "AUDIO_CODEC_UNSPECIFIED";
    case AudioCodec.AUDIO_CODEC_MP3:
      return "AUDIO_CODEC_MP3";
    case AudioCodec.AUDIO_CODEC_WAV:
      return "AUDIO_CODEC_WAV";
    case AudioCodec.AUDIO_CODEC_OPUS:
      return "AUDIO_CODEC_OPUS";
    case AudioCodec.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Enum representing supported audio formats */
export enum AudioFormat {
  AUDIO_FORMAT_UNSPECIFIED = 0,
  /** AUDIO_FORMAT_S16LE - Signed formats (little-endian) */
  AUDIO_FORMAT_S16LE = 1,
  UNRECOGNIZED = -1,
}

export function audioFormatFromJSON(object: any): AudioFormat {
  switch (object) {
    case 0:
    case "AUDIO_FORMAT_UNSPECIFIED":
      return AudioFormat.AUDIO_FORMAT_UNSPECIFIED;
    case 1:
    case "AUDIO_FORMAT_S16LE":
      return AudioFormat.AUDIO_FORMAT_S16LE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AudioFormat.UNRECOGNIZED;
  }
}

export function audioFormatToJSON(object: AudioFormat): string {
  switch (object) {
    case AudioFormat.AUDIO_FORMAT_UNSPECIFIED:
      return "AUDIO_FORMAT_UNSPECIFIED";
    case AudioFormat.AUDIO_FORMAT_S16LE:
      return "AUDIO_FORMAT_S16LE";
    case AudioFormat.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Configuration which describes Audio properties */
export interface AudioConfig {
  /** The audio codec */
  encoding: AudioCodec;
  /** Audio format */
  format?:
    | AudioFormat
    | undefined;
  /** Bitrate in kbps */
  bitrate_kbps?: number | undefined;
}

/**
 * AudioEncoding specifies parameters for encoding audio
 * Applicable to opus and mp3 only.
 */
export interface AudioEncoding {
  /** Bitrate in kbps */
  bitrate_kbps: number;
}

function createBaseAudioConfig(): AudioConfig {
  return { encoding: 0, format: undefined, bitrate_kbps: undefined };
}

export const AudioConfig: MessageFns<AudioConfig> = {
  encode(message: AudioConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.encoding !== 0) {
      writer.uint32(8).int32(message.encoding);
    }
    if (message.format !== undefined) {
      writer.uint32(16).int32(message.format);
    }
    if (message.bitrate_kbps !== undefined) {
      writer.uint32(24).uint32(message.bitrate_kbps);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.encoding = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.format = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.bitrate_kbps = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AudioConfig {
    return {
      encoding: isSet(object.encoding) ? audioCodecFromJSON(object.encoding) : 0,
      format: isSet(object.format) ? audioFormatFromJSON(object.format) : undefined,
      bitrate_kbps: isSet(object.bitrate_kbps) ? globalThis.Number(object.bitrate_kbps) : undefined,
    };
  },

  toJSON(message: AudioConfig): unknown {
    const obj: any = {};
    if (message.encoding !== 0) {
      obj.encoding = audioCodecToJSON(message.encoding);
    }
    if (message.format !== undefined) {
      obj.format = audioFormatToJSON(message.format);
    }
    if (message.bitrate_kbps !== undefined) {
      obj.bitrate_kbps = Math.round(message.bitrate_kbps);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioConfig>, I>>(base?: I): AudioConfig {
    return AudioConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioConfig>, I>>(object: I): AudioConfig {
    const message = createBaseAudioConfig();
    message.encoding = object.encoding ?? 0;
    message.format = object.format ?? undefined;
    message.bitrate_kbps = object.bitrate_kbps ?? undefined;
    return message;
  },
};

function createBaseAudioEncoding(): AudioEncoding {
  return { bitrate_kbps: 0 };
}

export const AudioEncoding: MessageFns<AudioEncoding> = {
  encode(message: AudioEncoding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bitrate_kbps !== 0) {
      writer.uint32(8).uint32(message.bitrate_kbps);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioEncoding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioEncoding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bitrate_kbps = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AudioEncoding {
    return { bitrate_kbps: isSet(object.bitrate_kbps) ? globalThis.Number(object.bitrate_kbps) : 0 };
  },

  toJSON(message: AudioEncoding): unknown {
    const obj: any = {};
    if (message.bitrate_kbps !== 0) {
      obj.bitrate_kbps = Math.round(message.bitrate_kbps);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioEncoding>, I>>(base?: I): AudioEncoding {
    return AudioEncoding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioEncoding>, I>>(object: I): AudioEncoding {
    const message = createBaseAudioEncoding();
    message.bitrate_kbps = object.bitrate_kbps ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
